//! Metadata operation allowlist for provider-visible evidence projection.
//!
//! These operations return durable metadata, refs, lifecycle, or status records
//! that the model can use without seeing raw content-bearing payloads.

pub(super) fn projects_metadata_operation(operation: &str) -> bool {
    matches!(
        operation,
        "goal_create"
            | "goal_list"
            | "goal_inspect"
            | "goal_cancel"
            | "question_create"
            | "question_list"
            | "question_inspect"
            | "question_answer"
            | "state_get"
            | "state_set"
            | "state_list"
            | "filesystem_write"
            | "filesystem_edit"
            | "filesystem_apply_patch"
            | "media_create"
            | "media_list"
            | "media_inspect"
            | "media_archive"
            | "memory_status"
            | "memory_list"
            | "memory_inspect"
            | "memory_query_list"
            | "memory_query_inspect"
            | "memory_decision_list"
            | "memory_decision_inspect"
            | "import_history_record"
            | "import_history_list"
            | "import_history_inspect"
            | "repository_tree_snapshot"
            | "repository_tree_list"
            | "repository_tree_inspect"
            | "import_preview_record"
            | "import_preview_list"
            | "import_preview_inspect"
            | "program_execution_record"
            | "program_execution_list"
            | "program_execution_inspect"
            | "prompt_artifact_record"
            | "prompt_artifact_list"
            | "prompt_artifact_inspect"
            | "update_diagnostic_record"
            | "update_diagnostic_list"
            | "update_diagnostic_inspect"
            | "web_research_request_record"
            | "web_research_request_list"
            | "web_research_request_inspect"
            | "web_research_review_record"
            | "web_research_review_list"
            | "web_research_review_inspect"
            | "web_research_source_record"
            | "web_research_source_list"
            | "web_research_source_inspect"
            | "module_list"
            | "module_inspect"
            | "module_proposal_record"
            | "module_proposal_list"
            | "module_proposal_inspect"
            | "module_validation_record"
            | "module_validation_list"
            | "module_validation_inspect"
            | "module_install_request_record"
            | "module_install_request_list"
            | "module_install_request_inspect"
            | "module_install_decision_record"
            | "module_install_decision_list"
            | "module_install_decision_inspect"
            | "module_dependency_request_record"
            | "module_dependency_request_list"
            | "module_dependency_request_inspect"
            | "module_dependency_decision_record"
            | "module_dependency_decision_list"
            | "module_dependency_decision_inspect"
            | "module_dependency_policy_activate"
            | "module_dependency_policy_list"
            | "module_dependency_policy_inspect"
            | "module_lifecycle_request"
            | "module_lifecycle_decision"
            | "module_lifecycle_list"
            | "module_lifecycle_inspect"
            | "module_runtime_request"
            | "module_runtime_list"
            | "module_runtime_inspect"
            | "module_runtime_cancel"
            | "module_program_execution_start"
            | "module_program_execution_status"
            | "module_program_execution_cancel"
            | "module_program_execution_cleanup"
            | "procedural_definition_record"
            | "procedural_state_list"
            | "procedural_state_inspect"
            | "procedural_activation_request_record"
            | "procedural_activation_request_list"
            | "procedural_activation_request_inspect"
            | "procedural_activation_decision_record"
            | "procedural_activation_decision_list"
            | "procedural_activation_decision_inspect"
            | "tool_source_list"
            | "tool_source_inspect"
            | "worker_package_list"
            | "worker_package_inspect"
    )
}
