use super::*;

#[test]
fn tron_event_all_event_types() {
    // Verify every variant has a distinct event_type
    let base = BaseEvent::now("s1");
    let events: Vec<TronEvent> = vec![
        TronEvent::AgentStart { base: base.clone() },
        TronEvent::AgentEnd {
            base: base.clone(),
            error: None,
        },
        TronEvent::AgentReady { base: base.clone() },
        TronEvent::SessionProcessingChanged {
            base: base.clone(),
            is_processing: true,
        },
        TronEvent::AgentInterrupted {
            base: base.clone(),
            turn: 1,
            partial_content: None,
            active_capability: None,
        },
        TronEvent::TurnStart {
            base: base.clone(),
            turn: 1,
        },
        TronEvent::TurnEnd {
            base: base.clone(),
            turn: 1,
            duration: 0,
            token_usage: None,
            token_record: None,
            cost: None,
            stop_reason: None,
            context_limit: None,
            model: None,
        },
        TronEvent::TurnFailed {
            base: base.clone(),
            turn: 1,
            error: "e".into(),
            code: None,
            category: None,
            recoverable: false,
            partial_content: None,
        },
        TronEvent::ResponseComplete {
            base: base.clone(),
            turn: 1,
            stop_reason: "end_turn".into(),
            token_usage: None,
            has_capability_invocations: false,
            capability_invocation_count: 0,
            token_record: None,
            model: None,
        },
        TronEvent::MessageUpdate {
            base: base.clone(),
            content: "c".into(),
        },
        TronEvent::CapabilityInvocationBatch {
            base: base.clone(),
            capability_invocations: vec![],
        },
        TronEvent::CapabilityInvocationStarted {
            base: base.clone(),
            invocation_id: "id".into(),
            model_primitive_name: "n".into(),
            arguments: None,
            capability_identity: CapabilityEventIdentity::default(),
        },
        TronEvent::CapabilityInvocationOutput {
            base: base.clone(),
            invocation_id: "id".into(),
            update: "u".into(),
        },
        TronEvent::CapabilityInvocationProgress {
            base: base.clone(),
            invocation_id: "id".into(),
            message: Some("msg".into()),
            percent: Some(0.5),
            capability_identity: CapabilityEventIdentity::default(),
        },
        TronEvent::CapabilityResolution {
            base: base.clone(),
            invocation_id: "id".into(),
            model_primitive_name: "execute".into(),
            requested_contract_id: Some("filesystem::read_file".into()),
            requested_implementation_id: None,
            requested_function_id: None,
            capability_identity: CapabilityEventIdentity::with_model_primitive("execute"),
        },
        TronEvent::CapabilityPauseRequested {
            base: base.clone(),
            pause_id: "pause-1".into(),
            invocation_id: "id".into(),
            kind: "user_input".into(),
            status: "pending".into(),
            prompt_payload: json!({"questions": []}),
            resume_schema: None,
            answer_authority: "user".into(),
            expires_at: None,
            capability_identity: CapabilityEventIdentity::default(),
        },
        TronEvent::CapabilityPauseResolved {
            base: base.clone(),
            pause_id: "pause-1".into(),
            invocation_id: "id".into(),
            status: "resumed".into(),
            resolution: Some(json!({"answers": []})),
            capability_identity: CapabilityEventIdentity::default(),
        },
        TronEvent::CapabilityRunStatus {
            base: base.clone(),
            run_id: "run-1".into(),
            invocation_id: "id".into(),
            status: "running".into(),
            stream_topic: Some("capability.run.run-1".into()),
            child_invocations: vec![],
            details: None,
            capability_identity: CapabilityEventIdentity::default(),
        },
        TronEvent::CapabilityInvocationCompleted {
            base: base.clone(),
            invocation_id: "id".into(),
            model_primitive_name: "n".into(),
            duration: 0,
            is_error: None,
            result: None,
            capability_identity: CapabilityEventIdentity::default(),
        },
        TronEvent::CapabilityInvocationArgumentDelta {
            base: base.clone(),
            invocation_id: "id".into(),
            model_primitive_name: None,
            arguments_delta: "d".into(),
        },
        TronEvent::CapabilityInvocationGenerating {
            base: base.clone(),
            invocation_id: "id".into(),
            model_primitive_name: "n".into(),
            capability_identity: CapabilityEventIdentity::default(),
        },
        TronEvent::HookTriggered {
            base: base.clone(),
            hook_names: vec![],
            hook_event: "e".into(),
            model_primitive_name: None,
            invocation_id: None,
        },
        TronEvent::HookCompleted {
            base: base.clone(),
            hook_names: vec![],
            hook_event: "e".into(),
            result: HookResult::Continue,
            duration: None,
            reason: None,
            model_primitive_name: None,
            invocation_id: None,
        },
        TronEvent::HookBackgroundStarted {
            base: base.clone(),
            hook_names: vec![],
            hook_event: "e".into(),
            execution_id: "id".into(),
        },
        TronEvent::HookBackgroundCompleted {
            base: base.clone(),
            hook_names: vec![],
            hook_event: "e".into(),
            execution_id: "id".into(),
            result: BackgroundHookResult::Continue,
            duration: 0,
            error: None,
        },
        TronEvent::LlmHookResult {
            base: base.clone(),
            hook_name: "test".into(),
            hook_id: "test-id".into(),
            hook_event: "sessionStart".into(),
            output: Some("title".into()),
            duration_ms: 100,
            model: "m".into(),
            input_tokens: 10,
            output_tokens: 5,
            success: true,
            error: None,
            suggestions: None,
        },
        TronEvent::SessionSaved {
            base: base.clone(),
            file_path: "p".into(),
        },
        TronEvent::SessionLoaded {
            base: base.clone(),
            file_path: "p".into(),
            message_count: 0,
        },
        TronEvent::ContextWarning {
            base: base.clone(),
            usage_percent: 80.0,
            message: "m".into(),
        },
        TronEvent::CompactionStart {
            base: base.clone(),
            reason: CompactionReason::Manual,
            tokens_before: 0,
        },
        TronEvent::CompactionComplete {
            base: base.clone(),
            success: true,
            tokens_before: 100,
            tokens_after: 50,
            compression_ratio: 0.5,
            reason: None,
            summary: None,
            estimated_context_tokens: None,
            preserved_turns: None,
            summarized_turns: None,
        },
        TronEvent::Error {
            base: base.clone(),
            error: "e".into(),
            context: None,
            code: None,
            provider: None,
            category: None,
            suggestion: None,
            retryable: None,
            status_code: None,
            error_type: None,
            model: None,
        },
        TronEvent::ApiRetry {
            base: base.clone(),
            attempt: 1,
            max_retries: 3,
            delay_ms: 1000,
            error_category: "c".into(),
            error_message: "m".into(),
        },
        TronEvent::ThinkingStart { base: base.clone() },
        TronEvent::ThinkingDelta {
            base: base.clone(),
            delta: "d".into(),
        },
        TronEvent::ThinkingEnd {
            base: base.clone(),
            thinking: "t".into(),
        },
        TronEvent::SessionCreated {
            base: base.clone(),
            model: "m".into(),
            working_directory: "/tmp".into(),
            source: None,
            profile: None,
            title: None,
        },
        TronEvent::SessionArchived { base: base.clone() },
        TronEvent::SessionUnarchived { base: base.clone() },
        TronEvent::SessionForked {
            base: base.clone(),
            new_session_id: "new-s1".into(),
        },
        TronEvent::SessionDeleted { base: base.clone() },
        TronEvent::SessionUpdated {
            base: base.clone(),
            title: None,
            model: Some("m".into()),
            event_count: Some(0),
            turn_count: Some(0),
            message_count: Some(0),
            input_tokens: Some(0),
            output_tokens: Some(0),
            last_turn_input_tokens: Some(0),
            cache_read_tokens: Some(0),
            cache_creation_tokens: Some(0),
            cost: Some(0.0),
            last_activity: "t".into(),
            is_active: true,
            last_user_prompt: None,
            last_assistant_response: None,
            parent_session_id: None,
            activity_lines: None,
        },
        TronEvent::MemoryUpdating { base: base.clone() },
        TronEvent::MemoryUpdated {
            base: base.clone(),
            title: None,
            summary: None,
            entry_type: None,
            event_id: None,
            resource_refs: None,
        },
        TronEvent::MemoryAutoRetainTriggered {
            base: base.clone(),
            interval_fired: 5,
        },
        TronEvent::MemoryAutoRetainFailed {
            base: base.clone(),
            interval_fired: 5,
            reason: "subagent error".into(),
        },
        TronEvent::ContextCleared {
            base: base.clone(),
            tokens_before: 0,
            tokens_after: 0,
        },
        TronEvent::MessageDeleted {
            base: base.clone(),
            target_event_id: "id".into(),
            target_type: "t".into(),
            target_turn: None,
            reason: None,
        },
        TronEvent::MessageQueued {
            base: base.clone(),
            queue_id: "q1".into(),
            text: "hello".into(),
            position: 0,
        },
        TronEvent::MessageDequeued {
            base: base.clone(),
            queue_id: "q1".into(),
            reason: "processed".into(),
        },
        TronEvent::QueuedMessageSent {
            base: base.clone(),
            text: "hello".into(),
            queue_id: "q1".into(),
        },
        TronEvent::RulesLoaded {
            base: base.clone(),
            total_files: 3,
            dynamic_rules_count: 1,
        },
        TronEvent::RulesActivated {
            base: base.clone(),
            rules: vec![ActivatedRuleInfo {
                relative_path: "src/.claude/CLAUDE.md".into(),
                scope_dir: "src".into(),
            }],
            total_activated: 1,
        },
        TronEvent::SkillActivated {
            base: base.clone(),
            skill_name: "browser".into(),
            source: "global".into(),
        },
        TronEvent::SkillDeactivated {
            base: base.clone(),
            skill_name: "browser".into(),
        },
        TronEvent::SubagentSpawned {
            base: base.clone(),
            subagent_session_id: "sub-1".into(),
            task: "t".into(),
            model: "m".into(),
            max_turns: 50,
            spawn_depth: 0,
            invocation_id: None,
            blocking_timeout_ms: Some(300_000),
            working_directory: None,
            spawn_type: None,
        },
        TronEvent::SubagentStatusUpdate {
            base: base.clone(),
            subagent_session_id: "sub-1".into(),
            status: "running".into(),
            current_turn: 1,
            activity: None,
        },
        TronEvent::SubagentCompleted {
            base: base.clone(),
            subagent_session_id: "sub-1".into(),
            total_turns: 3,
            duration: 5000,
            full_output: None,
            result_summary: None,
            token_usage: None,
            model: None,
            spawn_type: None,
        },
        TronEvent::SubagentFailed {
            base: base.clone(),
            subagent_session_id: "sub-1".into(),
            error: "e".into(),
            duration: 1000,
            spawn_type: None,
        },
        TronEvent::SubagentEvent {
            base: base.clone(),
            subagent_session_id: "sub-1".into(),
            event: json!({"type": "text_delta", "data": {"delta": "hi"}}),
        },
        TronEvent::SubagentResultAvailable {
            base: base.clone(),
            parent_session_id: "p1".into(),
            subagent_session_id: "sub-1".into(),
            task: "t".into(),
            result_summary: "done".into(),
            success: true,
            total_turns: 2,
            duration: 3000,
            token_usage: None,
            error: None,
            completed_at: "2024-01-01T00:00:00Z".into(),
            notify: true,
        },
        TronEvent::WorktreeAcquired {
            base: base.clone(),
            path: "/repo/.worktrees/session/abc".into(),
            branch: "session/abc".into(),
            base_commit: "deadbeef".into(),
            base_branch: Some("main".into()),
        },
        TronEvent::WorktreeCommit {
            base: base.clone(),
            commit_hash: "cafebabe".into(),
            message: "wip".into(),
            files_changed: vec!["file.txt".into()],
            insertions: 10,
            deletions: 2,
            total_commit_count: 3,
            has_uncommitted_changes: false,
        },
        TronEvent::WorktreeMerged {
            base: base.clone(),
            source_branch: "session/abc".into(),
            target_branch: "main".into(),
            merge_commit: Some("12345678".into()),
            strategy: "merge".into(),
        },
        TronEvent::WorktreeReleased {
            base: base.clone(),
            final_commit: Some("cafebabe".into()),
            branch_preserved: true,
            deleted: true,
        },
        TronEvent::WorktreeRenamed {
            base: base.clone(),
            old_branch: "session/abc123".into(),
            new_branch: "session/fuzzy-purple-elephant".into(),
        },
        TronEvent::DisplayFrame {
            base: base.clone(),
            stream_id: "stream-1".into(),
            invocation_id: "call-1".into(),
            data: "base64data".into(),
            frame_id: 1,
            width: 1280,
            height: 720,
        },
        TronEvent::ProcessSpawned {
            base: base.clone(),
            process_id: "proc-1".into(),
            label: "test".into(),
            kind: "shell".into(),
            background: false,
            invocation_id: "tc-1".into(),
        },
        TronEvent::ProcessStatusUpdate {
            base: base.clone(),
            process_id: "proc-1".into(),
            status: "background".into(),
        },
        TronEvent::ProcessCompleted {
            base: base.clone(),
            parent_session_id: "s1".into(),
            process_id: "proc-1".into(),
            label: "test".into(),
            success: true,
            exit_code: Some(0),
            duration: 100,
            result_summary: "ok".into(),
            blob_id: None,
            completed_at: "2026-01-01T00:00:00Z".into(),
        },
        TronEvent::JobBackgrounded {
            base: base.clone(),
            job_id: "proc-1".into(),
            reason: "auto_timeout".into(),
            label: "test".into(),
            invocation_id: "tc-1".into(),
        },
        TronEvent::WorktreeMainSynced {
            base: base.clone(),
            main_branch: "main".into(),
            old_head: "abc".into(),
            new_head: "def".into(),
            advanced_by: 3,
        },
        TronEvent::WorktreeSessionFinalized {
            base: base.clone(),
            source_branch: "session/1".into(),
            target_branch: "main".into(),
            merge_commit: Some("def".into()),
            strategy: "merge".into(),
            new_branch: "session/1/next".into(),
            new_base_commit: "def".into(),
            old_branch_deleted: false,
            old_branch_delete_error: None,
        },
        TronEvent::WorktreeMergeStarted {
            base: base.clone(),
            source_branch: "session/1".into(),
            target_branch: "main".into(),
            strategy: "merge".into(),
            conflict_count: 2,
        },
        TronEvent::WorktreeConflictDetected {
            base: base.clone(),
            source_branch: "session/1".into(),
            target_branch: "main".into(),
            origin: "finalize".into(),
            paths: vec!["f.txt".into()],
        },
        TronEvent::WorktreeConflictResolved {
            base: base.clone(),
            path: "f.txt".into(),
            resolution: "ours".into(),
            remaining: 0,
        },
        TronEvent::WorktreeMergeContinued {
            base: base.clone(),
            merge_commit: "def".into(),
            strategy: "merge".into(),
            origin: "finalize".into(),
        },
        TronEvent::WorktreeMergeAborted {
            base: base.clone(),
            strategy: "merge".into(),
            reason: "user".into(),
            origin: "finalize".into(),
        },
        TronEvent::WorktreePushed {
            base: base.clone(),
            branch: "session/1".into(),
            remote: "origin".into(),
            set_upstream: true,
            dry_run: false,
            force_with_lease: false,
        },
        TronEvent::WorktreePendingMergeDetected {
            base: base.clone(),
            source_branch: "session/1".into(),
            target_branch: "main".into(),
            strategy: "merge".into(),
            origin: "finalize".into(),
            started_at_ms: 0,
            auto_abort_at_ms: 0,
        },
        TronEvent::WorktreeRebasedOnMain {
            base: base.clone(),
            main_branch: "main".into(),
            strategy: "rebase".into(),
            old_base_commit: "abc".into(),
            new_base_commit: "def".into(),
            main_commits_incorporated: 1,
            had_auto_stash: false,
        },
        TronEvent::WorktreePostRebaseStashConflict {
            base: base.clone(),
            stash_ref: "stash@{0}".into(),
            paths: vec!["f.txt".into()],
        },
        TronEvent::WorktreeAutoRecoveredCommits {
            base: base.clone(),
            branch: "session/abc".into(),
            commit_hash: "cafebabe".into(),
            path: "/repo/.worktrees/session/abc".into(),
            branch_removed: true,
        },
        TronEvent::RepoLockAcquired {
            base: base.clone(),
            repo_root: "/repo".into(),
            session_id: "s1".into(),
            op: "syncMain".into(),
        },
        TronEvent::RepoLockReleased {
            base: base.clone(),
            repo_root: "/repo".into(),
            session_id: "s1".into(),
            op: "syncMain".into(),
        },
        TronEvent::RepoMainAdvanced {
            base,
            repo_root: "/repo".into(),
            old_head: "abc".into(),
            new_head: "def".into(),
            source_session_id: "s1".into(),
            cause: "sync".into(),
        },
    ];

    assert_eq!(events.len(), VARIANT_COUNT);

    let mut types: Vec<&str> = events.iter().map(TronEvent::event_type).collect();
    types.sort_unstable();
    types.dedup();
    assert_eq!(types.len(), VARIANT_COUNT);
}
