//! OpenAI model catalog shard.

use std::collections::HashMap;

use super::super::*;

#[allow(unused_results)]
pub(super) fn insert(m: &mut HashMap<&'static str, OpenAIModelInfo>) {
    m.insert(
        "gpt-5-chat-latest",
        model(
            "gpt-5-chat-latest",
            "GPT-5 Chat",
            "GPT-5 Chat",
            "GPT-5",
            "standard",
            "Retired GPT-5 model used in ChatGPT, exposed for chat testing.",
            &[],
            vec![platform_text_profile(
                128_000,
                16_384,
                true,
                true,
                1.25,
                10.0,
                Some(0.125),
            )],
            43,
            false,
            true,
            true,
            None,
            Some("gpt-5.1"),
            false,
            false,
            Some("2024-09-30"),
        ),
    );

    m.insert(
        "o3",
        model(
            "o3",
            "o3",
            "o3",
            "o-series",
            "flagship",
            "Reasoning model for complex tasks, succeeded by GPT-5.",
            &["o3-2025-04-16"],
            vec![platform_profile(
                200_000,
                Some(200_000),
                100_000,
                true,
                true,
                true,
                false,
                false,
                false,
                REASONING_LOW_TO_HIGH,
                "medium",
                2.0,
                8.0,
                Some(0.50),
                true,
            )],
            50,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2024-06-01"),
        ),
    );

    m.insert(
        "o3-pro",
        model(
            "o3-pro",
            "o3 Pro",
            "o3 Pro",
            "o-series",
            "flagship",
            "Higher-compute o3 variant; hidden because it does not support streaming Responses.",
            &["o3-pro-2025-06-10"],
            vec![platform_non_streaming_profile(
                200_000,
                100_000,
                true,
                true,
                REASONING_LOW_TO_HIGH,
                "high",
                20.0,
                80.0,
            )],
            51,
            false,
            true,
            false,
            None,
            None,
            true,
            false,
            Some("2024-06-01"),
        ),
    );

    m.insert(
        "o4-mini",
        model(
            "o4-mini",
            "o4 Mini",
            "o4 Mini",
            "o-series",
            "standard",
            "Fast, cost-efficient reasoning model, succeeded by GPT-5 mini.",
            &["o4-mini-2025-04-16"],
            vec![platform_profile(
                200_000,
                Some(200_000),
                100_000,
                true,
                true,
                true,
                false,
                false,
                false,
                REASONING_LOW_TO_HIGH,
                "medium",
                1.10,
                4.40,
                Some(0.275),
                true,
            )],
            52,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2024-06-01"),
        ),
    );

    m.insert(
        "o3-mini",
        model(
            "o3-mini",
            "o3 Mini",
            "o3 Mini",
            "o-series",
            "standard",
            "Small reasoning model for technical domains.",
            &["o3-mini-2025-01-31"],
            vec![platform_profile(
                200_000,
                Some(200_000),
                100_000,
                true,
                true,
                false,
                false,
                false,
                false,
                REASONING_LOW_TO_HIGH,
                "medium",
                1.10,
                4.40,
                Some(0.55),
                true,
            )],
            53,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2023-10-01"),
        ),
    );

    m.insert(
        "o1",
        model(
            "o1",
            "o1",
            "o1",
            "o-series",
            "flagship",
            "Previous full o-series reasoning model.",
            &["o1-2024-12-17"],
            vec![platform_profile(
                200_000,
                Some(200_000),
                100_000,
                true,
                true,
                true,
                false,
                false,
                false,
                REASONING_LOW_TO_HIGH,
                "medium",
                15.0,
                60.0,
                Some(7.50),
                true,
            )],
            54,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2023-10-01"),
        ),
    );

    m.insert(
        "o1-mini",
        model(
            "o1-mini",
            "o1 Mini",
            "o1 Mini",
            "o-series",
            "standard",
            "Retired small o1 reasoning model.",
            &["o1-mini-2024-09-12"],
            vec![platform_text_profile(
                128_000,
                65_536,
                false,
                false,
                1.10,
                4.40,
                Some(0.55),
            )],
            55,
            false,
            true,
            true,
            None,
            Some("o3-mini"),
            false,
            false,
            Some("2023-10-01"),
        ),
    );

    m.insert(
        "o1-preview",
        model(
            "o1-preview",
            "o1 Preview",
            "o1 Preview",
            "o-series",
            "flagship",
            "Retired research preview of the first o-series reasoning model.",
            &["o1-preview-2024-09-12"],
            vec![platform_text_profile(
                128_000,
                32_768,
                false,
                false,
                15.0,
                60.0,
                Some(7.50),
            )],
            56,
            false,
            true,
            true,
            None,
            Some("o1"),
            false,
            true,
            Some("2023-10-01"),
        ),
    );

    m.insert(
        "o1-pro",
        model(
            "o1-pro",
            "o1 Pro",
            "o1 Pro",
            "o-series",
            "flagship",
            "Higher-compute o1 variant; hidden because it does not support streaming Responses.",
            &["o1-pro-2025-03-19"],
            vec![platform_non_streaming_profile(
                200_000,
                100_000,
                true,
                true,
                REASONING_LOW_TO_HIGH,
                "high",
                150.0,
                600.0,
            )],
            57,
            false,
            true,
            false,
            None,
            None,
            true,
            false,
            Some("2023-10-01"),
        ),
    );

    m.insert(
        "gpt-4.1",
        model(
            "gpt-4.1",
            "GPT-4.1",
            "GPT-4.1",
            "GPT-4.1",
            "standard",
            "GPT-4.1 text and vision model with a long Platform Responses context window.",
            &["gpt-4.1-2025-04-14"],
            vec![platform_text_profile(
                1_047_576,
                32_768,
                true,
                true,
                2.0,
                8.0,
                Some(0.50),
            )],
            60,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2024-06-01"),
        ),
    );

    m.insert(
        "gpt-4.1-mini",
        model(
            "gpt-4.1-mini",
            "GPT-4.1 Mini",
            "GPT-4.1 Mini",
            "GPT-4.1",
            "standard",
            "Smaller GPT-4.1 model for fast, low-cost Platform Responses workloads.",
            &["gpt-4.1-mini-2025-04-14"],
            vec![platform_text_profile(
                1_047_576,
                32_768,
                true,
                true,
                0.40,
                1.60,
                Some(0.10),
            )],
            61,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2024-06-01"),
        ),
    );

    m.insert(
        "gpt-4.1-nano",
        model(
            "gpt-4.1-nano",
            "GPT-4.1 Nano",
            "GPT-4.1 Nano",
            "GPT-4.1",
            "standard",
            "Lowest-cost GPT-4.1 model for lightweight Platform Responses workloads.",
            &["gpt-4.1-nano-2025-04-14"],
            vec![platform_text_profile(
                1_047_576,
                32_768,
                true,
                true,
                0.10,
                0.40,
                Some(0.025),
            )],
            62,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2024-06-01"),
        ),
    );
}
