//! OpenAI model catalog shard.

use std::collections::HashMap;

use super::super::*;

#[allow(unused_results)]
pub(super) fn insert(m: &mut HashMap<&'static str, OpenAIModelInfo>) {
    m.insert(
        "gpt-5-mini",
        model(
            "gpt-5-mini",
            "GPT-5 Mini",
            "GPT-5 Mini",
            "GPT-5",
            "standard",
            "Cost-efficient GPT-5 model for well-defined low-latency workloads.",
            &["gpt-5-mini-2025-08-07"],
            vec![platform_reasoning_profile(
                400_000,
                128_000,
                true,
                true,
                false,
                false,
                REASONING_MINIMAL_TO_HIGH,
                "medium",
                0.25,
                2.0,
                Some(0.025),
            )],
            13,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2024-05-31"),
        ),
    );

    m.insert(
        "gpt-5-nano",
        model(
            "gpt-5-nano",
            "GPT-5 Nano",
            "GPT-5 Nano",
            "GPT-5",
            "standard",
            "Fastest, lowest-cost GPT-5 model for simple classification and extraction tasks.",
            &["gpt-5-nano-2025-08-07"],
            vec![platform_reasoning_profile(
                400_000,
                128_000,
                true,
                true,
                false,
                false,
                REASONING_MINIMAL_TO_HIGH,
                "medium",
                0.05,
                0.40,
                Some(0.005),
            )],
            14,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2024-05-31"),
        ),
    );

    m.insert(
        "gpt-5-pro",
        model(
            "gpt-5-pro",
            "GPT-5 Pro",
            "GPT-5 Pro",
            "GPT-5",
            "flagship",
            "Higher-compute GPT-5 variant that streams on the Platform Responses API.",
            &["gpt-5-pro-2025-10-06"],
            vec![platform_profile(
                400_000,
                Some(400_000),
                272_000,
                true,
                true,
                true,
                false,
                false,
                false,
                REASONING_HIGH_ONLY,
                "high",
                15.0,
                120.0,
                None,
                true,
            )],
            15,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2024-09-30"),
        ),
    );

    m.insert(
        "gpt-5-codex",
        model(
            "gpt-5-codex",
            "GPT-5 Codex",
            "GPT-5 Codex",
            "GPT-5",
            "flagship",
            "Retired GPT-5 coding model optimized for agentic coding on the Platform API.",
            &[],
            vec![platform_reasoning_profile(
                400_000,
                128_000,
                true,
                true,
                false,
                false,
                REASONING_LOW_TO_HIGH,
                "medium",
                1.25,
                10.0,
                Some(0.125),
            )],
            16,
            false,
            true,
            true,
            None,
            Some("gpt-5.3-codex"),
            false,
            false,
            Some("2024-09-30"),
        ),
    );

    m.insert(
        "gpt-5.2-codex",
        model(
            "gpt-5.2-codex",
            "GPT-5.2 Codex",
            "GPT-5.2",
            "GPT-5.2",
            "flagship",
            "Retired GPT-5.2 Codex model; use gpt-5.2 for new work.",
            &[],
            vec![platform_reasoning_profile(
                400_000,
                128_000,
                true,
                true,
                false,
                false,
                REASONING_LOW_TO_XHIGH,
                "medium",
                1.75,
                14.0,
                Some(0.175),
            )],
            20,
            false,
            true,
            true,
            Some("2026-04-14"),
            Some("gpt-5.2"),
            false,
            false,
            None,
        ),
    );

    m.insert(
        "gpt-5.1-codex",
        model(
            "gpt-5.1-codex",
            "GPT-5.1 Codex",
            "GPT-5.1 Codex",
            "GPT-5.1",
            "flagship",
            "Retired GPT-5.1 coding model optimized for agentic coding.",
            &[],
            vec![platform_reasoning_profile(
                400_000,
                128_000,
                true,
                true,
                false,
                false,
                REASONING_LOW_TO_HIGH,
                "medium",
                1.25,
                10.0,
                Some(0.125),
            )],
            21,
            false,
            true,
            true,
            Some("2026-04-14"),
            Some("gpt-5.3-codex"),
            false,
            false,
            Some("2024-09-30"),
        ),
    );

    m.insert(
        "gpt-5.1-codex-max",
        model(
            "gpt-5.1-codex-max",
            "GPT-5.1 Codex Max",
            "GPT-5.1 Max",
            "GPT-5.1",
            "flagship",
            "Retired deep-reasoning Codex model; use gpt-5.2 or newer.",
            &[],
            vec![platform_reasoning_profile(
                400_000,
                128_000,
                true,
                true,
                false,
                false,
                REASONING_LOW_TO_XHIGH,
                "high",
                1.25,
                10.0,
                Some(0.125),
            )],
            30,
            false,
            true,
            true,
            Some("2026-04-14"),
            Some("gpt-5.2"),
            false,
            false,
            None,
        ),
    );

    m.insert(
        "gpt-5.1-codex-mini",
        model(
            "gpt-5.1-codex-mini",
            "GPT-5.1 Codex Mini",
            "GPT-5.1 Mini",
            "GPT-5.1",
            "standard",
            "Retired fast Codex model; use gpt-5.4-mini or newer.",
            &[],
            vec![platform_reasoning_profile(
                400_000,
                128_000,
                true,
                true,
                false,
                false,
                REASONING_LOW_TO_HIGH,
                "low",
                0.25,
                2.0,
                Some(0.025),
            )],
            31,
            false,
            true,
            true,
            Some("2026-04-14"),
            Some("gpt-5.4-mini"),
            false,
            false,
            None,
        ),
    );

    m.insert(
        "codex-mini-latest",
        model(
            "codex-mini-latest",
            "Codex Mini Latest",
            "Codex Mini",
            "Codex",
            "standard",
            "Retired fast reasoning model optimized for the Codex CLI.",
            &[],
            vec![platform_reasoning_profile(
                200_000,
                100_000,
                true,
                true,
                false,
                false,
                REASONING_LOW_TO_HIGH,
                "medium",
                1.50,
                6.0,
                Some(0.375),
            )],
            32,
            false,
            true,
            true,
            None,
            Some("gpt-4.1"),
            false,
            false,
            Some("2024-06-01"),
        ),
    );

    m.insert(
        "gpt-5.3-chat-latest",
        model(
            "gpt-5.3-chat-latest",
            "GPT-5.3 Chat",
            "GPT-5.3 Chat",
            "GPT-5.3",
            "standard",
            "GPT-5.3 instant model used in ChatGPT, exposed on the Platform API for chat testing.",
            &[],
            vec![platform_text_profile(
                128_000,
                16_384,
                true,
                true,
                1.75,
                14.0,
                Some(0.175),
            )],
            40,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2025-08-31"),
        ),
    );

    m.insert(
        "gpt-5.2-chat-latest",
        model(
            "gpt-5.2-chat-latest",
            "GPT-5.2 Chat",
            "GPT-5.2 Chat",
            "GPT-5.2",
            "standard",
            "GPT-5.2 model used in ChatGPT, exposed on the Platform API for chat testing.",
            &[],
            vec![platform_text_profile(
                128_000,
                16_384,
                true,
                true,
                1.75,
                14.0,
                Some(0.175),
            )],
            41,
            false,
            true,
            false,
            None,
            None,
            false,
            false,
            Some("2025-08-31"),
        ),
    );

    m.insert(
        "gpt-5.1-chat-latest",
        model(
            "gpt-5.1-chat-latest",
            "GPT-5.1 Chat",
            "GPT-5.1 Chat",
            "GPT-5.1",
            "standard",
            "Retired GPT-5.1 model used in ChatGPT, exposed for chat testing.",
            &[],
            vec![platform_text_profile(
                128_000,
                16_384,
                true,
                true,
                1.25,
                10.0,
                Some(0.125),
            )],
            42,
            false,
            true,
            true,
            None,
            Some("gpt-5.1"),
            false,
            false,
            Some("2024-09-30"),
        ),
    );
}
