//! Static gates for the hyper modular agent architecture planning scorecard.
//!
//! This test stays separate from `threat_model_invariants.rs` so the broad
//! north-star planning guard does not grow the already-budgeted cross-cutting
//! invariant file.

use std::path::PathBuf;

#[test]
fn hyper_modular_architecture_plan_stays_formalized() {
    let repo_root = repo_root();
    let scorecard_path =
        repo_root.join("packages/agent/docs/hyper-modular-agent-architecture-scorecard.md");
    let portfolio_path =
        repo_root.join("packages/agent/docs/hyper-modular-agent-harness-execution-scorecards.md");
    let scorecard = std::fs::read_to_string(&scorecard_path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", scorecard_path.display()));
    let portfolio = std::fs::read_to_string(&portfolio_path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", portfolio_path.display()));
    let readme = std::fs::read_to_string(repo_root.join("README.md")).expect("read README.md");
    let primitive_surface = std::fs::read_to_string(repo_root.join(
        "packages/agent/src/domains/capability_support/implementations/primitive_surface.rs",
    ))
    .expect("read primitive_surface.rs");
    let capability_contract = std::fs::read_to_string(
        repo_root.join("packages/agent/src/domains/capability/contract.rs"),
    )
    .expect("read capability contract");
    let sandbox_contract =
        std::fs::read_to_string(repo_root.join("packages/agent/src/domains/sandbox/contract.rs"))
            .expect("read sandbox contract");
    let readme_harness_section = readme
        .split("Agents do not need to inspect Tron source to create a local worker.")
        .nth(1)
        .expect("README must document worker protocol guide loop");

    assert!(
        readme.contains("packages/agent/docs/hyper-modular-agent-architecture-scorecard.md")
            && readme.contains(
                "completed planning scorecard for the iii-informed hyper modular agent harness"
            )
            && readme.contains(
                "packages/agent/docs/hyper-modular-agent-harness-execution-scorecards.md"
            )
            && readme.contains("fresh execution scorecard portfolio"),
        "README living-doc map must link the hyper modular planning and execution scorecards"
    );

    for required in [
        "Current score: **100/100**",
        "Status: **completed planning artifact**",
        "Implementation execution status: **not started by this planning scorecard**",
        "/Users/moose/.codex/attachments/0af3ea78-c386-4055-ba8d-6e04c8eb5c49/pasted-text.txt",
        "/Users/moose/.codex/attachments/053a570d-434a-4879-bb93-1db134477b7c/pasted-text.txt",
        "`iii worker add` is the important product operation",
        "The agent and the human use the same operation to extend the same system",
        "The harness is a stack of workers, not a framework block.",
        "https://iii.dev/manifesto",
        "https://iii.dev/docs/0-10-0/primitives-and-concepts/functions-triggers-workers",
        "https://iii.dev/docs/0-10-0/primitives-and-concepts/discovery",
        "https://iii.dev/docs/0-10-0/how-to/use-functions-and-triggers",
        "https://iii.dev/docs/0-10-0/how-to/trigger-actions",
        "https://github.com/iii-hq/iii",
        "packages/agent/src/engine/mod.rs",
        "packages/agent/src/domains/capability/mod.rs",
        "packages/agent/src/domains/sandbox/mod.rs",
        "packages/ios-app/docs/architecture.md",
        "packages/agent/docs/hyper-modular-agent-harness-execution-scorecards.md",
        "## North-Star Requirements",
        "## Primitive And Plane Budget",
        "## Execution Scorecard Portfolio",
        "| HMA-B | Agent self-modifying capability lifecycle |",
        "| HMA-C | Harness knowledge and context compiler |",
        "| HMA-E | Human harness and generated UI north star |",
        "| HMA-F | Causality, safety, loops, and rollback |",
        "## Required Scenario Rows For HMA-B",
        "## Required Scenario Rows For HMA-E",
        "## Adversarial Audit",
        "| HMA-6 | Closeout verification | 10 | passed |",
        "The planning artifact is closed.",
    ] {
        assert!(
            scorecard.contains(required),
            "hyper modular planning scorecard missing required text: {required}"
        );
    }

    for forbidden in [
        "The attached pasted files available in this thread were not the iii articles.",
        "Status: **active until closeout verification**",
        "| HMA-6 | Closeout verification | 10 | pending |",
        "Then update HMA-6",
    ] {
        assert!(
            !scorecard.contains(forbidden),
            "completed planning scorecard must not retain active closeout text: {forbidden}"
        );
    }

    for required in [
        "# Hyper Modular Agent Harness Execution Scorecard Portfolio",
        "Current score: **95/100**",
        "Status: **running**",
        "## Source-Derived Requirements",
        "The agent and the human use the same operation to extend the same system.",
        "The harness is a composition slider, not a thin-vs-thick fork.",
        "https://iii.dev/docs/0-10-0/primitives-and-concepts/functions-triggers-workers",
        "https://iii.dev/docs/0-10-0/primitives-and-concepts/discovery",
        "https://iii.dev/docs/0-10-0/how-to/use-functions-and-triggers",
        "https://iii.dev/docs/0-10-0/how-to/trigger-actions",
        "https://iii.dev/docs/0-10-0/how-to/use-queues",
        "https://iii.dev/docs/0-10-0/advanced/protocol",
        "https://iii.dev/docs/quickstart",
        "https://iii.dev/docs/workers/managed-worker-lockfile",
        "https://github.com/iii-hq/iii",
        "## Current Tron Baseline",
        "## Primitive And Plane Budget",
        "## Operating Loop",
        "| HMH-A | Source, baseline, and primitive audit | 10 | passed |",
        "| HMH-B | Agent self-modifying capability lifecycle | 20 | passed |",
        "| HMH-C | Harness knowledge and context compiler | 15 | passed |",
        "| HMH-D | Plug-and-play module/package lifecycle | 15 | passed |",
        "| HMH-E | Human harness and generated UI | 15 | passed_after_fix |",
        "| HMH-F | Causality, safety, loops, and rollback | 15 | passed_after_fix |",
        "| HMH-G | Final adversarial closeout and absence gates | 10 | pending |",
        "| HMH-A1 | Attachment synthesis is first-class source | 20 | passed |",
        "| HMH-A2 | Public iii facts verified | 15 | passed |",
        "| HMH-A3 | Current Tron substrate map is evidence-backed | 25 | passed |",
        "| HMH-A4 | Primitive/plane budget accepted | 20 | passed |",
        "| HMH-A5 | Prior scorecards treated as prerequisites only | 10 | passed |",
        "| HMH-A6 | Fresh execution portfolio linked and guarded | 10 | passed |",
        "HMH-A closeout evidence, 2026-06-02:",
        "## HMH-B Scorecard: Agent Self-Modifying Capability Lifecycle",
        "| HMH-B1 | Model is taught the lifecycle | 10 | passed_after_fix |",
        "HMH-B1 evidence, 2026-06-02:",
        "The fix keeps guidance in the existing model-facing surfaces",
        "| HMH-B2 | Worker guide is sufficient | 10 | passed_after_fix |",
        "HMH-B2 evidence, 2026-06-02:",
        "as the profile-backed agent actor while server-owned execution policy scopes",
        "| HMH-B3 | Session worker creation is scoped | 15 | passed |",
        "HMH-B3 evidence, 2026-06-02:",
        "| HMH-B4 | Live catalog update and inspection work | 10 | passed |",
        "HMH-B4 evidence, 2026-06-02:",
        "| HMH-B5 | Conformance/test evidence is resource-backed | 10 | passed_after_fix |",
        "HMH-B5 evidence, 2026-06-02:",
        "`capability::conformance_run` now creates an `evidence` resource",
        "declares a resource-backed `evidence` output contract",
        "capability_self_modifying_lifecycle_records_session_worker_conformance_evidence",
        "| HMH-B6 | Invocation uses the tiny harness | 15 | passed |",
        "HMH-B6 evidence, 2026-06-02:",
        "`observability::trace_get` with full payloads shows exactly three functions",
        "`engine::invoke`, `capability::execute`, and the generated",
        "capability_self_modifying_lifecycle_invokes_session_worker_through_execute",
        "| HMH-B7 | Promotion is governed | 10 | passed_after_fix |",
        "HMH-B7 evidence, 2026-06-02:",
        "`expectedFunctionRevision` returns `STALE_FUNCTION_REVISION`",
        "clean authority scopes",
        "capability_self_modifying_lifecycle_governs_session_worker_promotion",
        "| HMH-B8 | Cleanup and stale calls fail closed | 10 | passed |",
        "HMH-B8 evidence, 2026-06-02:",
        "`function_unregistered` change for the session",
        "`worker_unregistered` change for the volatile",
        "returns structured `needs_capability` guidance",
        "`childInvocationCreated=false`",
        "shows only `engine::invoke` and `capability::execute`",
        "capability_self_modifying_lifecycle_cleans_up_session_worker_and_stale_calls_fail_closed",
        "local_external_worker_durable_disconnect_marks_functions_unhealthy",
        "| HMH-B9 | Agent explains the evidence | 10 | passed |",
        "HMH-B9 evidence, 2026-06-02:",
        "A deterministic provider first emits a model `execute` invocation targeting",
        "On the second provider",
        "payload includes the current function id, worker id, plugin id",
        "`executeInvocationId`",
        "`childInvocationIds`",
        "governed promotion with `expectedFunctionRevision`",
        "cleanup through `sandbox::stop_spawned_worker` or",
        "contains no README-only explanation",
        "capability_self_modifying_lifecycle_explains_session_worker_evidence",
        "Open loops after HMH-B1/HMH-B2/HMH-B3/HMH-B4/HMH-B5/HMH-B6/HMH-B7/HMH-B8/HMH-B9:",
        "HMH-B is closed.",
        "## HMH-C Scorecard: Harness Knowledge And Context Compiler",
        "| HMH-C1 | Primer contains the north-star recipe | 20 | passed_after_fix |",
        "HMH-C1 evidence, 2026-06-02:",
        "initially failed after the C1 test was strengthened to require generated",
        "`ui::surface_for_target`",
        "`ui::inspect_surface`",
        "`ui::submit_action`",
        "stored surface/version/action ids",
        "The fix keeps the recipe in the fixed `capabilities.primer` header",
        "README's worker-protocol section now matches the primer",
        "Open loops after HMH-C1:",
        "| HMH-C2 | Context budget remains bounded | 15 | passed_after_fix |",
        "HMH-C2 evidence, 2026-06-02:",
        "initially failed with a `2633` estimated-token primer",
        "profile `2600` token budget",
        "primer over budget",
        "requires the bounded primer to preserve worker",
        "`module::register_package`",
        "worker_package",
        "source trust",
        "`module::activate`",
        "`module::run_conformance`",
        "reserves `TRUNCATION_NOTICE` before adding another rendered catalog",
        "| HMH-C3 | Execute correction covers lifecycle errors | 20 | passed_after_fix |",
        "HMH-C3 evidence, 2026-06-02:",
        "`refresh_capability_revision`",
        "stable `provide_idempotency_key` guidance object",
        "bare approval-required results carry their `approvalId`",
        "| HMH-C4 | Harness docs are resources | 15 | passed_after_fix |",
        "HMH-C4 evidence, 2026-06-02:",
        "built-in resource kind owned by the",
        "session-scoped versioned `harness_doc` resource",
        "inspectTarget=resource::inspect",
        "| HMH-C5 | Model-run proof across providers | 20 | passed_after_fix |",
        "HMH-C5 evidence, 2026-06-02:",
        "Provider::OpenAi",
        "Provider::Ollama",
        "no prompt-expanded",
        "harness_docs_are_versioned_resources",
        "model_run_proves_harness_customization_across_providers",
        "provider_prompt_surface_stays_tiny",
        "| HMH-C6 | Prompt surface stays tiny | 10 | passed_after_fix |",
        "HMH-C6 evidence, 2026-06-02:",
        "rogue::execute",
        "pins model-facing capability primitives to the canonical",
        "Open loops after HMH-C1/HMH-C2/HMH-C3/HMH-C4/HMH-C5/HMH-C6:",
        "HMH-C is closed",
        "HMH-D, HMH-E1, HMH-E2, HMH-E3, HMH-E4, HMH-E5, and HMH-E6 are also",
        "closed; continue with HMH-E7 to prove disconnected cache submissions fail",
        "module package/config/activation/",
        "trust/health/action projections",
        "module_register_package_validates_digest_namespace_and_contracts",
        "## HMH-D Scorecard: Plug-And-Play Module/Package Lifecycle",
        "| HMH-D1 | Package registration is resource-backed | 10 | passed |",
        "HMH-D1 evidence, 2026-06-02:",
        "local-process package, then inspects",
        "`worker-package:demo-local-resource-backed` through `resource::inspect`",
        "must be kind `worker_package`, owned by the",
        "must carry the normalized",
        "`runtimeEntryPoint` worker id",
        "raw `apiKey: sk-test-secret` runtime material",
        "HMH-D2 evidence, 2026-06-02:",
        "`module_source_approval_ceiling_denies_overbroad_activation_before_spawn`",
        "fails with a source-approval ceiling violation",
        "The full source-trust suite covers activation denial before verification",
        "trust-root renewal",
        "signature-key rotation links",
        "HMH-D3 evidence, 2026-06-02:",
        "not holding a host lock that deadlocks",
        "The same proof now asserts the exact `worker::spawn` payload",
        "It inspects the derived grant and verifies parent grant lineage",
        "`activation_record` resource to verify current version",
        "e2e_local_process_module_activation_health_and_disable_use_real_worker_spawn",
        "HMH-D4 evidence, 2026-06-02:",
        "`module_run_conformance_links_evidence_and_updates_package_policy`",
        "records the child invocation id in `healthResult`",
        "`policyDiagnostics.conformance.evidenceRef`",
        "surfaces manual recovery when spawned-worker",
        "HMH-D5 evidence, 2026-06-02:",
        "`module_upgrade_and_rollback_require_current_version_before_spawn_and_replay`",
        "`module_quarantine_stale_activation_fails_before_stop_and_blocks_stale_grant`",
        "`module_local_process_replacement_spawn_failure_marks_activation_failed_closed`",
        "expected-version rejection before extra spawn/stop",
        "`module::rollback` now uses the same replacement-source cleanup path",
        "Replacement local-process upgrades and rollbacks now stop the superseded",
        "`runtimeDiagnostics.recoveryStatus=failed_closed`",
        "scopes its child",
        "HMH-D6 evidence, 2026-06-02:",
        "`module_local_package_install_shape_is_resource_backed_and_rejects_implicit_remote_trust`",
        "install packaged modules",
        "`module::register_package` over `worker_package` resources",
        "unsupported `remote_url` package provenance",
        "| HMH-D7 | iOS/operator projection is complete | 10 | passed_after_fix |",
        "HMH-D7 evidence, 2026-06-02:",
        "`ControlSnapshotDTO` did not decode the server's `moduleHealth`",
        "`moduleOperatorProjection`",
        "EngineConsoleModuleProjection.swift",
        "server-advertised `module::` action",
        "does not keep a package-policy",
        "EngineConsoleModuleProjectionCard",
        "TronMobileTests/EngineConsoleStateTests",
        "TronMobileTests/SourceGuardTests",
        "HMH-D8 evidence, 2026-06-02:",
        "module::package_action",
        "module::mutate_package",
        "module_action_multiplexer",
        "package_action_multiplexer",
        "generic_package_mutation",
        "client-side module policy/action ownership",
        "there is no generic `module::act` or",
        "Open loops after HMH-D1/HMH-D2/HMH-D3/HMH-D4/HMH-D5/HMH-D6/HMH-D7/HMH-D8:",
        "HMH-D and HMH-E1 through HMH-E7 are closed. Continue with HMH-F1 to prove",
        "conflicting idempotency before handler execution.",
        "module_activate_local_process_invokes_worker_spawn_and_records_integrity",
        "| HMH-D2 | Source trust is explicit and revocable | 15 | passed |",
        "| HMH-D3 | Activation composes worker spawn | 15 | passed |",
        "| HMH-D4 | Health, integrity, and conformance are inspectable | 15 | passed |",
        "| HMH-D5 | Upgrade, rollback, disable, quarantine work | 15 | passed |",
        "| HMH-D6 | Local marketplace shape exists | 10 | passed |",
        "generated_ui_can_author_package_and_activation_operator_surfaces",
        "| HMH-D8 | No generic action escape hatch | 10 | passed_after_fix |",
        "## HMH-E Scorecard: Human Harness And Generated UI",
        "| HMH-E1 | Engine Console is substrate-first | 15 | passed_after_fix |",
        "HMH-E1 evidence, 2026-06-02:",
        "fixed Swift mini catalog",
        "EngineConsoleState.substrateSearchSuggestions",
        "server substrate state: status/index primer context, registry",
        "control-advertised actions",
        "generated `ui_surface` refs",
        "redacted audit event/trace ids",
        "searchSuggestionsProjectLiveSubstrate",
        "EngineConsoleSuggestionChips(suggestions: state.substrateSearchSuggestions)",
        "TronMobileTests/EngineConsoleAccessibilityTests",
        "HMH-E2 evidence, 2026-06-02:",
        "ui_surface_for_session_generated_capability_submits_stored_action_coordinates",
        "GeneratedUIRendererTests.sessionGeneratedCapabilitySurfaceRendersAndSubmitsCoordinates",
        "| HMH-E2 | Generated surface for new capability | 20 | passed_after_fix |",
        "| HMH-E3 | Approval and consequence clarity | 15 | passed_after_fix |",
        "HMH-E3 evidence, 2026-06-02:",
        "EngineApprovalTargetMetadata",
        "target_metadata_json",
        "targetMetadata",
        "ApprovalClient.resolve -> approval::resolve",
        "TronMobileTests/EngineApprovalStateTests",
        "TronMobileTests/ApprovalClientTests",
        "| HMH-E4 | Module controls are native projections | 15 | passed_after_fix |",
        "HMH-E4 evidence, 2026-06-02:",
        "configure-package",
        "activate-package",
        "disable-activation",
        "upgrade-activation",
        "rollback-activation",
        "quarantine-activation",
        "EngineConsoleModuleSurfaceTarget",
        "`ui::surface_for_target`",
        "`ui::submit_action`",
        "generated_ui_can_author_package_and_activation_operator_surfaces",
        "TronMobileTests/EngineConsoleStateTests",
        "TronMobileTests/GeneratedUIRendererTests",
        "| HMH-E5 | Human can understand agent-created harness changes | 15 | passed_after_fix |",
        "HMH-E5 evidence, 2026-06-02:",
        "EngineConsoleHarnessChangeProjection",
        "Harness Changes",
        "provenance, tests, generated UI, promotion, cleanup, and",
        "harnessChangeProjectionExplainsSessionCreatedCapabilityEvidence",
        "testHarnessChangeEvidenceCardStaysAccessible",
        "| HMH-E6 | Visual proof covers iPhone and iPad | 10 | passed_after_fix |",
        "HMH-E6 evidence, 2026-06-02/2026-06-03:",
        "TronMobileTests/EngineConsoleAccessibilityTests",
        "hmh-e6-simulator-install-launch-20260603T000331Z.json",
        "| HMH-E7 | Disconnected cache is read-only | 10 | passed_after_fix |",
        "HMH-E7 evidence, 2026-06-02/2026-06-03:",
        "Open loops after HMH-E1/HMH-E2/HMH-E3/HMH-E4/HMH-E5/HMH-E6/HMH-E7:",
        "HMH-E and HMH-F are closed. Continue with HMH-G1",
        "## HMH-F Scorecard: Causality, Safety, Loops, And Rollback",
        "| HMH-F1 | Idempotency is mandatory for mutations | 15 | passed |",
        "| HMH-F2 | Approval resume preserves original context |",
        "| HMH-F2 | Approval resume preserves original context | 15 | passed |",
        "HMH-F2 evidence, 2026-06-03:",
        "approval_required_execute_resumes_child_with_original_causal_context",
        "| HMH-F3 | Trigger delivery modes are bounded | 15 | passed_after_fix |",
        "HMH-F3 evidence, 2026-06-03:",
        "engine.triggerDepth",
        "runtime_metadata_json",
        "direct Void invocations remain unsupported even if they forge trigger",
        "| HMH-F4 | Queue/DLQ is inspectable | 15 | passed_after_fix |",
        "HMH-F4 evidence, 2026-06-03:",
        "EngineQueueAttemptRecord",
        "attempt_records_json",
        "replayedFromInvocationId",
        "| HMH-F5 | Leases and compensation are visible | 15 | passed_after_fix |",
        "HMH-F5 evidence, 2026-06-03:",
        "real_shared_mutation_contracts_declare_leases_and_compensation",
        "real_primitive_mutations_record_visible_leases_and_compensation",
        "ui_surface:lifecycle",
        "| HMH-F6 | Trace and ledger explain the full graph | 15 | passed_after_fix |",
        "HMH-F6 evidence, 2026-06-03:",
        "observability_trace_get_explains_full_client_agent_worker_ui_graph",
        "engine_queue_items(trace_id,",
        "engine_resource_events(trace_id,",
        "cargo test --manifest-path packages/agent/Cargo.toml engine::tests::state_queue -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml engine::tests::leases_compensation -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml engine::tests::trace_observability -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml engine::tests::external_worker -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml domains::capability::registry::tests::index -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml sqlite_registry_records_degraded_vector_metadata -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml sqlite_search_degrades_while_filtered_vectors_are_still_indexing -- --nocapture",
        "| HMH-F7 | Restart/disconnect chaos fails closed | 10 | passed_after_fix |",
        "HMH-F7 evidence, 2026-06-03:",
        "engine::tests::restart_chaos",
        "sqlite_restart_marks_durable_worker_unhealthy_without_socket_reconnect",
        "missing_approval_resolve_primitive_leaves_pending_child_unexecuted",
        "engine_catalog_workers",
        "engine_catalog_functions",
        "CAPABILITY_INDEX_UNAVAILABLE",
        "Open loops after HMH-F1/HMH-F2/HMH-F3/HMH-F4/HMH-F5/HMH-F6/HMH-F7:",
        "HMH-F is closed. Continue with HMH-G1",
        "## HMH-G Scorecard: Final Adversarial Closeout And Absence Gates",
        "| HMH-G1 | Requirement-by-requirement completion audit | 20 | passed_after_fix |",
        "HMH-G1 evidence, 2026-06-03:",
        "Requirement-by-requirement completion audit matrix",
        "Score math correction",
        "A-F closed total is 90 points",
        "HMH-G1 contributes 2 points",
        "objective: fully implement the execution portfolio",
        "objective: remove retired, fail-open bypass, dead, or parallel-plane logic",
        "source: iii live discovery",
        "source: agent and human use the same operation",
        "source: approval, policy, queue, and observability fail closed",
        "Final closeout criterion: clean end-to-end ordinary-agent run",
        "Open loops after HMH-G1:",
        "Continue with HMH-G2: prove absence gates are current",
        "| HMH-G2 | Absence gates are current | 15 | passed_after_fix |",
        "HMH-G2 evidence, 2026-06-03:",
        "current_architecture_terms_are_deleted_or_owned",
        "client policy/targets",
        "prompt-expanded tool catalogs",
        "discovery bypasses",
        "global dynamic visibility",
        "alternate spawn",
        "generic module actions",
        "stale scorecard states",
        "Open loops after HMH-G1/HMH-G2:",
        "Continue with HMH-G3: audit session transcripts",
        "| HMH-G3 | Transcript/session audit | 15 | passed |",
        "HMH-G3 evidence, 2026-06-03:",
        "Session audit index refreshed",
        "019e8780-9bf0-76c1-be22-9106bc24d32d",
        "019e8658-ee09-73b3-9b96-f640a1ed869d",
        "019e7a07-4b7f-77f2-b15b-242f2c005ca8",
        "Deduplicated active/archive transcript copies",
        "Command hygiene lessons",
        "Token-efficiency lessons",
        "No new successor rows are needed",
        "Open loops after HMH-G1/HMH-G2/HMH-G3:",
        "Continue with HMH-G4: rerun the clean live recursive loop",
        "| HMH-G7 | Ledger and final status are honest |",
        "## Adversarial Audit Of This Portfolio",
        "Modular in docs, not in the agent turn.",
        "Human harness as a second engine.",
        "Scorecard closure by rhetoric.",
        "## Static Gates",
        "## Final Closeout Criteria",
        "cargo test --manifest-path packages/agent/Cargo.toml --test hyper_modular_architecture_plan_invariants -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml capability_self_modifying_lifecycle_cleans_up_session_worker_and_stale_calls_fail_closed -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml capability_self_modifying_lifecycle_explains_session_worker_evidence -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml primer_teaches_self_modifying_worker_lifecycle -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml capability_primer_context_stays_within_budget -- --nocapture",
        "cargo test --manifest-path packages/agent/Cargo.toml execute_guidance_covers_self_modifying_lifecycle_errors -- --nocapture",
    ] {
        assert!(
            portfolio.contains(required),
            "hyper modular execution portfolio missing required text: {required}"
        );
    }

    for forbidden in [
        "The attached pasted files available in this thread were not the iii articles.",
        "Current score: **0/100**",
        "Status: **ready_for_execution**",
        "| HMH-A | Source, baseline, and primitive audit | 10 | pending |",
        "| HMH-B | Agent self-modifying capability lifecycle | 20 | pending |",
        "| HMH-A1 | Attachment synthesis is first-class source | 20 | pending |",
        "| HMH-B1 | Model is taught the lifecycle | 10 | pending |",
        "| HMH-B3 | Session worker creation is scoped | 15 | pending |",
        "| HMH-B4 | Live catalog update and inspection work | 10 | pending |",
        "| HMH-B5 | Conformance/test evidence is resource-backed | 10 | pending |",
        "| HMH-B6 | Invocation uses the tiny harness | 15 | pending |",
        "| HMH-B7 | Promotion is governed | 10 | pending |",
        "| HMH-B8 | Cleanup and stale calls fail closed | 10 | pending |",
        "| HMH-B9 | Agent explains the evidence | 10 | pending |",
        "| HMH-C | Harness knowledge and context compiler | 15 | pending |",
        "| HMH-C1 | Primer contains the north-star recipe | 20 | pending |",
        "| HMH-C2 | Context budget remains bounded | 15 | pending |",
        "| HMH-C3 | Execute correction covers lifecycle errors | 20 | pending |",
        "| HMH-C4 | Harness docs are resources | 15 | pending |",
        "| HMH-C5 | Model-run proof across providers | 20 | pending |",
        "| HMH-C6 | Prompt surface stays tiny | 10 | pending |",
        "Open loops after HMH-B1/HMH-B2/HMH-B3/HMH-B4/HMH-B5/HMH-B6/HMH-B7:",
        "Open loops after HMH-B1/HMH-B2/HMH-B3/HMH-B4/HMH-B5/HMH-B6/HMH-B7/HMH-B8:",
        "Continue with HMH-B8: prove cleanup unregisters or marks stale session-worker",
        "Continue with HMH-B9: prove the agent can explain live",
        "Continue with HMH-C1: prove the compact",
        "Continue with HMH-C2: prove the context",
        "Continue with HMH-C3",
        "Continue with HMH-C4",
        "Continue with HMH-C5",
        "Continue with HMH-C6",
        "Open loops after HMH-C1/HMH-C2/HMH-C3/HMH-C4/HMH-C5:",
        "Current score: **19/100**",
        "Current score: **21/100**",
        "Current score: **24/100**",
        "Current score: **26/100**",
        "Current score: **28/100**",
        "Current score: **30/100**",
        "Current score: **33/100**",
        "Current score: **35.25/100**",
        "Current score: **38.25/100**",
        "Current score: **40.5/100**",
        "Current score: **43.5/100**",
        "Current score: **45/100**",
        "Current score: **46.5/100**",
        "Current score: **48.75/100**",
        "Current score: **51/100**",
        "Current score: **53.25/100**",
        "Current score: **55.5/100**",
        "Current score: **57/100**",
        "Current score: **58.5/100**",
        "Current score: **60/100**",
        "Current score: **62.25/100**",
        "Current score: **65.25/100**",
        "Current score: **67.5/100**",
        "Current score: **82.5/100**",
        "Current score: **84.75/100**",
        "Current score: **90.00/100**",
        "Current score: **92.25/100**",
        "Current score: **93.5/100**",
        "Current score: **94.50/100**",
        "Current score: **99/100**",
        "Current score: **100/100**",
        "Status: **completed**",
        "| HMH-G1 | Requirement-by-requirement completion audit | 20 | pending |",
        "| HMH-G2 | Absence gates are current | 15 | pending |",
        "| HMH-G3 | Transcript/session audit | 15 | pending |",
        "| HMH-D1 | Package registration is resource-backed | 10 | pending |",
        "| HMH-D2 | Source trust is explicit and revocable | 15 | pending |",
        "| HMH-D3 | Activation composes worker spawn | 15 | pending |",
        "| HMH-D4 | Health, integrity, and conformance are inspectable | 15 | pending |",
        "| HMH-D5 | Upgrade, rollback, disable, quarantine work | 15 | pending |",
        "| HMH-D6 | Local marketplace shape exists | 10 | pending |",
        "| HMH-D7 | iOS/operator projection is complete | 10 | pending |",
        "| HMH-D8 | No generic action escape hatch | 10 | pending |",
        "| HMH-E1 | Engine Console is substrate-first | 15 | pending |",
        "| HMH-E2 | Generated surface for new capability | 20 | pending |",
        "| HMH-E3 | Approval and consequence clarity | 15 | pending |",
        "| HMH-E4 | Module controls are native projections | 15 | pending |",
        "| HMH-E5 | Human can understand agent-created harness changes | 15 | pending |",
        "Continue with HMH-D1",
        "Continue with HMH-D2",
        "Continue with HMH-D3",
        "Continue with HMH-D4",
        "Continue with HMH-D5",
        "Continue with HMH-D6",
        "Continue with HMH-D7",
        "Continue with HMH-D8",
        "Continue with HMH-E1",
        "Continue with HMH-E2",
        "Continue with HMH-E3: prove approval",
        "Continue with HMH-E4",
        "Continue with HMH-E5",
        "Continue with HMH-F2: prove approval",
        "Continue with HMH-F3",
        "Continue with HMH-F4",
        "Continue with HMH-F7",
        "| HMH-F2 | Approval resume preserves original context | 15 | pending |",
        "| HMH-F3 | Trigger delivery modes are bounded | 15 | pending |",
        "| HMH-F4 | Queue/DLQ is inspectable | 15 | pending |",
        "| HMH-F7 | Restart/disconnect chaos fails closed | 10 | pending |",
        "Open loops after HMH-F1:",
        "Open loops after HMH-F1/HMH-F2:",
        "Open loops after HMH-F1/HMH-F2/HMH-F3:",
        "Open loops after HMH-F1/HMH-F2/HMH-F3/HMH-F4/HMH-F5/HMH-F6:",
        "Open loops after HMH-E1:",
        "Open loops after HMH-E1/HMH-E2:",
        "Open loops after HMH-E1/HMH-E2/HMH-E3:",
        "Open loops after HMH-E1/HMH-E2/HMH-E3/HMH-E4:",
        "HMH-D remains open",
        "continue with HMH-D7",
        "continue with HMH-D2",
        "continue with HMH-D3",
        "continue with HMH-D4",
        "continue with HMH-D5",
        "continue with HMH-D6",
        "module_source_approval_revocation_and_conformance_are_resource_backed",
    ] {
        assert!(
            !portfolio.contains(forbidden),
            "execution portfolio must not claim completion or preserve forbidden plane text: {forbidden}"
        );
    }

    assert!(
        primitive_surface.contains("provider_surface_contains_only_capability_primitives")
            && primitive_surface
                .contains("assert_eq!(surface.all_model_capability_ids, [\"execute\"]);")
            && primitive_surface
                .contains("only the `capability` worker's `execute` orchestrator is exposed"),
        "provider surface must keep a concrete guard against prompt-expanded tool catalogs"
    );
    assert!(
        capability_contract.contains("fn only_execute_has_model_metadata()")
            && capability_contract
                .contains("assert!(model_metadata(SEARCH_FUNCTION_ID).is_null());")
            && capability_contract
                .contains("assert!(!model_metadata(EXECUTE_FUNCTION_ID).is_null());")
            && capability_contract.contains("admin_write_resource_backed_contract")
            && capability_contract.contains("CONFORMANCE_RUN_FUNCTION_ID")
            && capability_contract.contains("[\"evidence\"]"),
        "capability contract must guard execute as the only model metadata owner and conformance evidence as resource-backed"
    );
    assert!(
        sandbox_contract.contains("worker::spawn")
            && !sandbox_contract.contains("sandbox::spawn_worker"),
        "worker creation must remain canonical worker::spawn, not an alternate sandbox public API"
    );
    assert!(
        readme_harness_section.contains("Session visibility is the default")
            && readme_harness_section.contains("workspace/system")
            && readme_harness_section.contains("`engine::promote`")
            && readme_harness_section.contains("`ui::surface_for_target`")
            && readme_harness_section.contains("`ui::inspect_surface`")
            && readme_harness_section.contains("`ui::submit_action`")
            && readme_harness_section.contains("surface/version/action ids"),
        "README must document session-worker default visibility, generated UI handoff, and governed promotion"
    );
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("packages/agent parent")
        .parent()
        .expect("repo root")
        .to_path_buf()
}
