//! Frozen governance-family provider-visible presentation rows.

use super::OracleRow;

pub(super) const ROWS: [OracleRow; 59] = [
    (
        "procedural_definition_record",
        "governance",
        "Record Procedural Definition",
        "Record metadata for a skill, rule, hook, or procedure without activating it.",
    ),
    (
        "procedural_state_list",
        "governance",
        "List Procedural Definitions",
        "List scoped procedural definitions with bounded state and evaluation summaries.",
    ),
    (
        "procedural_state_inspect",
        "governance",
        "Inspect Procedural Definition",
        "Inspect one procedural definition's metadata, state, and evaluation evidence.",
    ),
    (
        "procedural_activation_request_record",
        "governance",
        "Request Procedural Activation",
        "Record a review request to activate, deactivate, or roll back a procedure.",
    ),
    (
        "procedural_activation_request_list",
        "governance",
        "List Procedural Activation Requests",
        "List scoped procedural activation requests with bounded review summaries.",
    ),
    (
        "procedural_activation_request_inspect",
        "governance",
        "Inspect Procedural Activation Request",
        "Inspect one procedural activation request and its validation evidence.",
    ),
    (
        "procedural_activation_decision_record",
        "governance",
        "Record Procedural Activation Decision",
        "Record a review decision without activating or executing the procedure.",
    ),
    (
        "procedural_activation_decision_list",
        "governance",
        "List Procedural Activation Decisions",
        "List scoped procedural activation decisions with bounded evidence summaries.",
    ),
    (
        "procedural_activation_decision_inspect",
        "governance",
        "Inspect Procedural Activation Decision",
        "Inspect one procedural activation decision and its rollback evidence.",
    ),
    (
        "schedule_create",
        "governance",
        "Create Schedule",
        "Create a durable schedule with bounded timing and target metadata.",
    ),
    (
        "schedule_list",
        "governance",
        "List Schedules",
        "List scoped schedules with bounded timing and lifecycle summaries.",
    ),
    (
        "schedule_inspect",
        "governance",
        "Inspect Schedule",
        "Inspect one schedule and its current timing and lifecycle state.",
    ),
    (
        "schedule_cancel",
        "governance",
        "Cancel Schedule",
        "Cancel one active schedule after freshness and idempotency checks.",
    ),
    (
        "schedule_fire_due",
        "governance",
        "Run Due Schedules",
        "Advance due schedules and record their bounded firing evidence.",
    ),
    (
        "tool_source_list",
        "governance",
        "List Tool Sources",
        "List inert tool-source proposals without installing or running them.",
    ),
    (
        "tool_source_inspect",
        "governance",
        "Inspect Tool Source",
        "Inspect one tool-source proposal or conformance report without activation.",
    ),
    (
        "subagent_launch",
        "governance",
        "Launch Subagent",
        "Launch a governed delegated task through the accepted supervised runtime.",
    ),
    (
        "subagent_status",
        "governance",
        "Inspect Subagent Status",
        "Inspect one delegated task and its supervised runtime status.",
    ),
    (
        "subagent_result",
        "governance",
        "Review Subagent Result",
        "Return a reviewable result proposal without mutating the parent conversation.",
    ),
    (
        "subagent_cancel",
        "governance",
        "Cancel Subagent",
        "Cancel one nonterminal delegated task through its supervised runtime.",
    ),
    (
        "subagent_task_list",
        "governance",
        "List Subagent Tasks",
        "List delegated task records with bounded lifecycle and handoff summaries.",
    ),
    (
        "subagent_task_inspect",
        "governance",
        "Inspect Subagent Task",
        "Inspect one delegated task's lifecycle, runtime, and handoff evidence.",
    ),
    (
        "worker_package_list",
        "governance",
        "List Worker Packages",
        "List worker-package lifecycle records without installing or running packages.",
    ),
    (
        "worker_package_inspect",
        "governance",
        "Inspect Worker Package",
        "Inspect one worker-package lifecycle record and its bounded evidence.",
    ),
    (
        "module_list",
        "governance",
        "List Modules",
        "List registered modules through bounded provider-safe manifest summaries.",
    ),
    (
        "module_inspect",
        "governance",
        "Inspect Module",
        "Inspect one registered module's bounded manifest and lifecycle metadata.",
    ),
    (
        "module_proposal_record",
        "governance",
        "Record Module Proposal",
        "Record inert module proposal metadata without installing or executing it.",
    ),
    (
        "module_proposal_list",
        "governance",
        "List Module Proposals",
        "List inert module proposals with bounded status and evidence summaries.",
    ),
    (
        "module_proposal_inspect",
        "governance",
        "Inspect Module Proposal",
        "Inspect one inert module proposal and its current evidence.",
    ),
    (
        "module_validation_record",
        "governance",
        "Record Module Validation",
        "Record module validation evidence without running or installing module code.",
    ),
    (
        "module_validation_list",
        "governance",
        "List Module Validations",
        "List module validation reports with bounded result summaries.",
    ),
    (
        "module_validation_inspect",
        "governance",
        "Inspect Module Validation",
        "Inspect one module validation report and its evidence.",
    ),
    (
        "module_install_request_record",
        "governance",
        "Request Module Installation",
        "Record a review request to install a validated module without installing it.",
    ),
    (
        "module_install_request_list",
        "governance",
        "List Module Installation Requests",
        "List module installation requests with bounded review state.",
    ),
    (
        "module_install_request_inspect",
        "governance",
        "Inspect Module Installation Request",
        "Inspect one module installation request and its validation evidence.",
    ),
    (
        "module_install_decision_record",
        "governance",
        "Record Module Installation Decision",
        "Record an installation review decision without installing or enabling the module.",
    ),
    (
        "module_install_decision_list",
        "governance",
        "List Module Installation Decisions",
        "List module installation decisions with bounded approval summaries.",
    ),
    (
        "module_install_decision_inspect",
        "governance",
        "Inspect Module Installation Decision",
        "Inspect one installation decision and its rollback evidence.",
    ),
    (
        "module_dependency_request_record",
        "governance",
        "Request Module Dependency",
        "Record a module dependency review request without restoring dependencies.",
    ),
    (
        "module_dependency_request_list",
        "governance",
        "List Module Dependency Requests",
        "List module dependency requests with bounded policy summaries.",
    ),
    (
        "module_dependency_request_inspect",
        "governance",
        "Inspect Module Dependency Request",
        "Inspect one module dependency request and its policy evidence.",
    ),
    (
        "module_dependency_decision_record",
        "governance",
        "Record Module Dependency Decision",
        "Record a dependency review decision without changing package state.",
    ),
    (
        "module_dependency_decision_list",
        "governance",
        "List Module Dependency Decisions",
        "List module dependency decisions with bounded approval summaries.",
    ),
    (
        "module_dependency_decision_inspect",
        "governance",
        "Inspect Module Dependency Decision",
        "Inspect one dependency decision and its policy evidence.",
    ),
    (
        "module_dependency_policy_activate",
        "governance",
        "Activate Module Dependency Policy",
        "Activate approved dependency policy metadata without restoring packages.",
    ),
    (
        "module_dependency_policy_list",
        "governance",
        "List Module Dependency Policies",
        "List active module dependency policies with bounded evidence summaries.",
    ),
    (
        "module_dependency_policy_inspect",
        "governance",
        "Inspect Module Dependency Policy",
        "Inspect one module dependency policy and its approval evidence.",
    ),
    (
        "module_lifecycle_request",
        "governance",
        "Request Module Lifecycle Change",
        "Request a governed module enable, disable, quarantine, or rollback transition.",
    ),
    (
        "module_lifecycle_decision",
        "governance",
        "Decide Module Lifecycle Change",
        "Apply an approved module lifecycle transition without running module code.",
    ),
    (
        "module_lifecycle_list",
        "governance",
        "List Module Lifecycle States",
        "List module lifecycle records with bounded authorization and rollback summaries.",
    ),
    (
        "module_lifecycle_inspect",
        "governance",
        "Inspect Module Lifecycle",
        "Inspect one module lifecycle record and its authorization evidence.",
    ),
    (
        "module_program_execution_start",
        "governance",
        "Start Module Program",
        "Start a supervised module-owned job through an authorized runtime.",
    ),
    (
        "module_program_execution_status",
        "governance",
        "Inspect Module Program Status",
        "Inspect a delegated module job through bounded runtime and output references.",
    ),
    (
        "module_program_execution_cancel",
        "governance",
        "Cancel Module Program",
        "Request cancellation of one delegated module job.",
    ),
    (
        "module_program_execution_cleanup",
        "governance",
        "Clean Up Module Program",
        "Archive one terminal delegated module job after freshness checks.",
    ),
    (
        "module_runtime_request",
        "governance",
        "Request Module Runtime",
        "Record a supervised runtime envelope for an enabled module.",
    ),
    (
        "module_runtime_list",
        "governance",
        "List Module Runtimes",
        "List supervised module runtimes with bounded lifecycle summaries.",
    ),
    (
        "module_runtime_inspect",
        "governance",
        "Inspect Module Runtime",
        "Inspect one supervised module runtime and its authorization evidence.",
    ),
    (
        "module_runtime_cancel",
        "governance",
        "Cancel Module Runtime",
        "Record cancellation of one active supervised module runtime.",
    ),
];
