//! Frozen records-family provider-visible presentation rows.

use super::OracleRow;

pub(super) const ROWS: [OracleRow; 63] = [
    (
        "goal_create",
        "records",
        "Create Goal",
        "Create a durable scoped goal with lifecycle and evidence references.",
    ),
    (
        "goal_list",
        "records",
        "List Goals",
        "List scoped goals with bounded lifecycle summaries and navigation references.",
    ),
    (
        "goal_inspect",
        "records",
        "Inspect Goal",
        "Inspect one scoped goal and its current lifecycle evidence.",
    ),
    (
        "goal_cancel",
        "records",
        "Cancel Goal",
        "Cancel one nonterminal goal after freshness and idempotency checks.",
    ),
    (
        "question_create",
        "records",
        "Ask User Question",
        "Create a durable scoped question with answer choices and expiry metadata.",
    ),
    (
        "question_list",
        "records",
        "List User Questions",
        "List scoped questions with bounded state and answer-navigation summaries.",
    ),
    (
        "question_inspect",
        "records",
        "Inspect User Question",
        "Inspect one scoped question and its current answer state.",
    ),
    (
        "question_answer",
        "records",
        "Record User Answer",
        "Record an idempotent answer handoff for one pending question.",
    ),
    (
        "memory_status",
        "records",
        "Inspect Memory Status",
        "Inspect current memory policy, engine identity, and prompt-inclusion state.",
    ),
    (
        "memory_list",
        "records",
        "List Memory Records",
        "List redacted memory records for the current session.",
    ),
    (
        "memory_inspect",
        "records",
        "Inspect Memory Record",
        "Inspect one redacted memory record and its version history.",
    ),
    (
        "memory_query_list",
        "records",
        "List Memory Queries",
        "List redacted memory-query evidence and ranked record references.",
    ),
    (
        "memory_query_inspect",
        "records",
        "Inspect Memory Query",
        "Inspect one redacted memory-query result and its retrieval evidence.",
    ),
    (
        "memory_decision_list",
        "records",
        "List Memory Decisions",
        "List memory inclusion decisions with bounded policy evidence.",
    ),
    (
        "memory_decision_inspect",
        "records",
        "Inspect Memory Decision",
        "Inspect one memory inclusion decision and its policy evidence.",
    ),
    (
        "context_control_status",
        "records",
        "Inspect Context Status",
        "Inspect current context composition, token estimates, references, and freshness.",
    ),
    (
        "context_control_snapshot",
        "records",
        "Snapshot Context",
        "Record a provider-safe snapshot of the current session context.",
    ),
    (
        "context_control_compact",
        "records",
        "Compact Context",
        "Record and apply a bounded context-compaction boundary without deleting history.",
    ),
    (
        "context_control_clear",
        "records",
        "Clear Active Context",
        "Start a new context epoch while preserving inspectable history and evidence.",
    ),
    (
        "context_control_action_list",
        "records",
        "List Context Actions",
        "List provider-safe summaries of context-control actions in the current session.",
    ),
    (
        "context_control_action_inspect",
        "records",
        "Inspect Context Action",
        "Inspect one context-control action and its preflight and result evidence.",
    ),
    (
        "context_survivor_record",
        "records",
        "Preserve Context Reference",
        "Record a safe reference that future context compaction must preserve.",
    ),
    (
        "context_survivor_list",
        "records",
        "List Preserved Context",
        "List active safe references that future context compaction must preserve.",
    ),
    (
        "context_survivor_disable",
        "records",
        "Stop Preserving Context",
        "Disable one active preserved-context policy after freshness checks.",
    ),
    (
        "context_exclusion_record",
        "records",
        "Exclude Context Reference",
        "Record a safe reference that future provider context must omit.",
    ),
    (
        "context_exclusion_list",
        "records",
        "List Excluded Context",
        "List active safe references that future provider context must omit.",
    ),
    (
        "context_exclusion_disable",
        "records",
        "Stop Excluding Context",
        "Disable one active context-exclusion policy after freshness checks.",
    ),
    (
        "context_policy_snapshot",
        "records",
        "Snapshot Context Policy",
        "Record the complete bounded set of active context inclusion and exclusion policies.",
    ),
    (
        "media_create",
        "records",
        "Create Media Artifact",
        "Create metadata and storage references for a scoped media artifact.",
    ),
    (
        "media_list",
        "records",
        "List Media Artifacts",
        "List scoped media artifacts with bounded storage and transcription summaries.",
    ),
    (
        "media_inspect",
        "records",
        "Inspect Media Artifact",
        "Inspect one media artifact's metadata, storage, lifecycle, and transcription state.",
    ),
    (
        "media_archive",
        "records",
        "Archive Media Artifact",
        "Archive one media artifact while preserving its lifecycle evidence.",
    ),
    (
        "import_history_record",
        "records",
        "Record Import History",
        "Record bounded lineage between imported session or resource references.",
    ),
    (
        "import_history_list",
        "records",
        "List Import History",
        "List scoped import-lineage records as bounded graph summaries.",
    ),
    (
        "import_history_inspect",
        "records",
        "Inspect Import History",
        "Inspect one import-lineage record and its evidence references.",
    ),
    (
        "import_preview_record",
        "records",
        "Record Import Preview",
        "Record a content-free preview linking import history and repository metadata.",
    ),
    (
        "import_preview_list",
        "records",
        "List Import Previews",
        "List content-free import previews with bounded counts and path summaries.",
    ),
    (
        "import_preview_inspect",
        "records",
        "Inspect Import Preview",
        "Inspect one content-free import preview and its linked evidence.",
    ),
    (
        "program_execution_record",
        "records",
        "Record Program Execution",
        "Record content-free program execution metadata without launching a runtime.",
    ),
    (
        "program_execution_list",
        "records",
        "List Program Executions",
        "List content-free program execution records and lifecycle summaries.",
    ),
    (
        "program_execution_inspect",
        "records",
        "Inspect Program Execution",
        "Inspect one content-free program execution record and its evidence.",
    ),
    (
        "prompt_artifact_record",
        "records",
        "Record Prompt Artifact",
        "Record opt-in prompt artifact metadata without storing the raw prompt body.",
    ),
    (
        "prompt_artifact_list",
        "records",
        "List Prompt Artifacts",
        "List opt-in prompt artifacts with bounded metadata and retention state.",
    ),
    (
        "prompt_artifact_inspect",
        "records",
        "Inspect Prompt Artifact",
        "Inspect one prompt artifact's metadata, references, and retention evidence.",
    ),
    (
        "update_diagnostic_record",
        "records",
        "Record Update Diagnostic",
        "Record signed-release and update-check metadata without installing an update.",
    ),
    (
        "update_diagnostic_list",
        "records",
        "List Update Diagnostics",
        "List bounded update diagnostics and signature status summaries.",
    ),
    (
        "update_diagnostic_inspect",
        "records",
        "Inspect Update Diagnostic",
        "Inspect one update diagnostic and its provenance and signature evidence.",
    ),
    (
        "device_list",
        "records",
        "List Devices",
        "List registered devices with bounded delivery and lifecycle metadata.",
    ),
    (
        "device_inspect",
        "records",
        "Inspect Device",
        "Inspect one registered device and its current delivery metadata.",
    ),
    (
        "notification_send",
        "records",
        "Send Notification",
        "Send one scoped notification through the registered delivery path.",
    ),
    (
        "notification_list",
        "records",
        "List Notifications",
        "List scoped notifications with bounded delivery and read-state summaries.",
    ),
    (
        "notification_inspect",
        "records",
        "Inspect Notification",
        "Inspect one notification's content metadata, delivery, and read state.",
    ),
    (
        "notification_mark_read",
        "records",
        "Mark Notification Read",
        "Mark one scoped notification as read after freshness checks.",
    ),
    (
        "notification_mark_all_read",
        "records",
        "Mark All Notifications Read",
        "Mark all eligible notifications in the current scope as read.",
    ),
    (
        "web_research_request_record",
        "records",
        "Record Web Research Request",
        "Record bounded web research intent and policy metadata without fetching sources.",
    ),
    (
        "web_research_request_list",
        "records",
        "List Web Research Requests",
        "List scoped web research requests without network or browser activity.",
    ),
    (
        "web_research_request_inspect",
        "records",
        "Inspect Web Research Request",
        "Inspect one web research request and its bounded policy references.",
    ),
    (
        "web_research_review_record",
        "records",
        "Record Web Research Review",
        "Record a bounded review linked to one web research request.",
    ),
    (
        "web_research_review_list",
        "records",
        "List Web Research Reviews",
        "List scoped web research reviews without network access.",
    ),
    (
        "web_research_review_inspect",
        "records",
        "Inspect Web Research Review",
        "Inspect one web research review and its evidence references.",
    ),
    (
        "web_research_source_record",
        "records",
        "Record Web Research Source",
        "Record bounded citation metadata linked to a research request or review.",
    ),
    (
        "web_research_source_list",
        "records",
        "List Web Research Sources",
        "List bounded citation artifacts linked to scoped web research.",
    ),
    (
        "web_research_source_inspect",
        "records",
        "Inspect Web Research Source",
        "Inspect one bounded research source and its citation references.",
    ),
];
