//! Frozen direct-family provider-visible presentation rows.

use super::OracleRow;

pub(super) const ROWS: [OracleRow; 41] = [
    (
        "observe",
        "direct",
        "Record Observation",
        "Add a bounded observation to the current assistant-visible work stream.",
    ),
    (
        "state_get",
        "direct",
        "Get State",
        "Read one value from engine-owned state in the current scope.",
    ),
    (
        "state_set",
        "direct",
        "Update State",
        "Write one value to engine-owned state in the current scope.",
    ),
    (
        "state_list",
        "direct",
        "List State",
        "List engine-owned state entries for a scope and namespace.",
    ),
    (
        "filesystem_read",
        "direct",
        "Read File",
        "Read a bounded text preview beneath the trusted workspace root.",
    ),
    (
        "filesystem_list",
        "direct",
        "List Files",
        "List bounded directory entries beneath the trusted workspace root.",
    ),
    (
        "filesystem_find",
        "direct",
        "Find Files",
        "Find bounded paths by name without following symbolic links.",
    ),
    (
        "filesystem_glob",
        "direct",
        "Match Files by Pattern",
        "Find bounded paths that match a workspace-relative glob pattern.",
    ),
    (
        "filesystem_search_text",
        "direct",
        "Search File Text",
        "Search bounded text previews while skipping binary file content.",
    ),
    (
        "filesystem_diff",
        "direct",
        "Preview File Changes",
        "Compare current file content with a proposed bounded text change.",
    ),
    (
        "filesystem_write",
        "direct",
        "Write File",
        "Preview or commit a guarded file write with verifiable evidence.",
    ),
    (
        "filesystem_edit",
        "direct",
        "Edit File",
        "Preview or commit one exact guarded text replacement.",
    ),
    (
        "filesystem_apply_patch",
        "direct",
        "Apply File Patch",
        "Apply an exact guarded text patch with bounded evidence.",
    ),
    (
        "git_status",
        "direct",
        "Inspect Git Status",
        "Inspect branch, upstream, and bounded working-tree status without changing the repository.",
    ),
    (
        "git_diff",
        "direct",
        "Inspect Git Changes",
        "Read bounded staged and unstaged change evidence without running external helpers.",
    ),
    (
        "git_branch_inventory",
        "direct",
        "List Git Branches",
        "List local branches, revisions, upstreams, and ahead or behind status.",
    ),
    (
        "git_stage",
        "direct",
        "Stage File",
        "Stage one explicit workspace-relative path after repository freshness checks.",
    ),
    (
        "git_unstage",
        "direct",
        "Unstage File",
        "Remove one explicit workspace-relative path from the Git index.",
    ),
    (
        "git_commit",
        "direct",
        "Create Git Commit",
        "Create one guarded commit from the already staged Git index.",
    ),
    (
        "git_branch_start",
        "direct",
        "Start Git Branch",
        "Create and select a new local branch without changing workspace content.",
    ),
    (
        "process_run",
        "direct",
        "Run Process",
        "Run a bounded local command with timeout, output, and no-network enforcement.",
    ),
    (
        "job_start",
        "direct",
        "Start Job",
        "Start a supervised durable command job with bounded output and lifecycle evidence.",
    ),
    (
        "job_status",
        "direct",
        "Inspect Job Status",
        "Inspect a durable job's redacted lifecycle, timing, and output references.",
    ),
    (
        "job_list",
        "direct",
        "List Jobs",
        "List durable jobs in the current scope with bounded lifecycle summaries.",
    ),
    (
        "job_log",
        "direct",
        "Read Job Output",
        "Read bounded standard-output and standard-error previews for one durable job.",
    ),
    (
        "job_cancel",
        "direct",
        "Cancel Job",
        "Request guarded cancellation of a running durable job.",
    ),
    (
        "trace_list",
        "direct",
        "List Execution Traces",
        "List bounded provider-safe execution traces for the current session.",
    ),
    (
        "trace_get",
        "direct",
        "Inspect Execution Trace",
        "Inspect one provider-safe execution trace by its exact record reference.",
    ),
    (
        "log_recent",
        "direct",
        "Read Recent Logs",
        "Read bounded recent engine log evidence with optional trace filtering.",
    ),
    (
        "replay_manifest",
        "direct",
        "Export Replay Manifest",
        "Export the current session's replay hashes and cross-record references.",
    ),
    (
        "catalog_search",
        "direct",
        "Search Capability Catalog",
        "Find visible operations and engine functions without invoking them.",
    ),
    (
        "catalog_inspect",
        "direct",
        "Inspect Capability Contract",
        "Inspect one operation, function, worker, or trigger contract without invoking it.",
    ),
    (
        "catalog_conformance",
        "direct",
        "Verify Capability Catalog",
        "Record a catalog conformance report and its verification evidence.",
    ),
    (
        "repository_tree_snapshot",
        "direct",
        "Snapshot Repository Tree",
        "Record content-free repository tree metadata, paths, references, and counts.",
    ),
    (
        "repository_tree_list",
        "direct",
        "List Repository Snapshots",
        "List content-free repository tree snapshots with bounded path previews.",
    ),
    (
        "repository_tree_inspect",
        "direct",
        "Inspect Repository Snapshot",
        "Inspect one content-free repository tree snapshot and its evidence.",
    ),
    (
        "web_fetch",
        "direct",
        "Fetch Web Source",
        "Fetch one explicit URL with declared network and robots-policy authority.",
    ),
    (
        "web_robots_check",
        "direct",
        "Check Web Robots Policy",
        "Check one origin's robots policy for an explicit requested URL.",
    ),
    (
        "web_source_list",
        "direct",
        "List Web Sources",
        "List citation-ready web source records without network access.",
    ),
    (
        "web_source_inspect",
        "direct",
        "Inspect Web Source",
        "Inspect one citation-ready web source and its bounded snippet evidence.",
    ),
    (
        "web_source_archive",
        "direct",
        "Archive Web Source",
        "Archive one web source while preserving its provenance evidence.",
    ),
];
