//! Capability contracts owned by the worktree domain worker.

#[allow(unused_imports)]
use serde_json::json;

use crate::engine::{
    CompensationContract, CompensationKind, EffectClass, IdempotencyContract,
    ResourceLeaseRequirement, Result as EngineResult, RiskLevel,
};
use crate::server::domains::catalog::CapabilitySpec;
use crate::server::domains::contract::CapabilityContract;

/// Canonical capability contracts exposed by this domain worker.
pub(crate) fn capabilities() -> EngineResult<Vec<CapabilitySpec>> {
    Ok(vec![
        CapabilityContract::new("worktree::get_status", "worktree", EffectClass::PureRead, RiskLevel::Low, Some("worktree.read"))
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .build()?,
        CapabilityContract::new("worktree::is_git_repo", "worktree", EffectClass::PureRead, RiskLevel::Low, Some("worktree.read"))
            .request_schema(json!({"additionalProperties":false,"properties":{"path":{"type":"string"},"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["path"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .build()?,
        CapabilityContract::new("worktree::commit", "worktree", EffectClass::ReversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .request_schema(json!({"additionalProperties":false,"properties":{"amend":{"type":"boolean"},"message":{"type":"string"},"sessionId":{"type":"string"},"signoff":{"type":"boolean"},"stageAll":{"type":"boolean"},"workspaceId":{"type":"string"}},"required":["sessionId","message","stageAll"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "git revert/reset is a manual recovery path after commit creation"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes high-risk branch/workflow mutations for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"git revert/reset is a manual recovery path after commit creation","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::merge", "worktree", EffectClass::ReversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"strategy":{"type":"string"},"targetBranch":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "merge abort or manual conflict recovery is available while merge state exists"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes high-risk branch/workflow mutations for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"merge abort or manual conflict recovery is available while merge state exists","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::list", "worktree", EffectClass::PureRead, RiskLevel::Low, Some("worktree.read"))
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .build()?,
        CapabilityContract::new("worktree::get_diff", "worktree", EffectClass::PureRead, RiskLevel::Low, Some("worktree.read"))
            .request_schema(json!({"additionalProperties":false,"properties":{"file":{"type":"string"},"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .build()?,
        CapabilityContract::new("worktree::acquire", "worktree", EffectClass::IdempotentWrite, RiskLevel::Medium, Some("worktree.write"))
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:assignment", 300000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "worktree release is the inverse command and duplicate acquire replays"))
            .build()?,
        CapabilityContract::new("worktree::release", "worktree", EffectClass::IdempotentWrite, RiskLevel::Medium, Some("worktree.write"))
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:assignment", 300000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "worktree acquire can recreate the assignment if needed"))
            .build()?,
        CapabilityContract::new("worktree::list_session_branches", "worktree", EffectClass::PureRead, RiskLevel::Low, Some("worktree.read"))
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .build()?,
        CapabilityContract::new("worktree::get_committed_diff", "worktree", EffectClass::PureRead, RiskLevel::Low, Some("worktree.read"))
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .build()?,
        CapabilityContract::new("worktree::finalize_session", "worktree", EffectClass::ReversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .domain_module("worktree::git_workflow")
            .request_schema(json!({"additionalProperties":false,"properties":{"newBranchName":{"type":"string"},"preserveOld":{"type":"boolean"},"rebranch":{"type":"boolean"},"sessionId":{"type":"string"},"sourceBranch":{"type":"string"},"strategy":{"type":"string"},"targetBranch":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "finalize uses all-or-none branch publication; manual branch cleanup may be required"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes high-risk branch/workflow mutations for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"finalize uses all-or-none branch publication; manual branch cleanup may be required","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::delete_branch", "worktree", EffectClass::IrreversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .request_schema(json!({"additionalProperties":false,"properties":{"branch":{"type":"string"},"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId","branch"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::ExternalIrreversible, "deleted local branches require reflog/remote recovery if still available"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes destructive branch/index mutations for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"deleted local branches require reflog/remote recovery if still available","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::prune_branches", "worktree", EffectClass::IrreversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::ExternalIrreversible, "pruned branches require manual branch restoration if needed"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes destructive branch/index mutations for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"pruned branches require manual branch restoration if needed","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::stage_files", "worktree", EffectClass::IdempotentWrite, RiskLevel::Medium, Some("worktree.write"))
            .request_schema(json!({"additionalProperties":false,"properties":{"paths":{"items":{"type":"string"},"type":"array"},"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId","paths"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:index", 300000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "worktree.unstageFiles is the inverse command"))
            .build()?,
        CapabilityContract::new("worktree::unstage_files", "worktree", EffectClass::IdempotentWrite, RiskLevel::Medium, Some("worktree.write"))
            .request_schema(json!({"additionalProperties":false,"properties":{"paths":{"items":{"type":"string"},"type":"array"},"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId","paths"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:index", 300000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "worktree.stageFiles is the inverse command"))
            .build()?,
        CapabilityContract::new("worktree::discard_files", "worktree", EffectClass::IrreversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .request_schema(json!({"additionalProperties":false,"properties":{"paths":{"items":{"type":"string"},"type":"array"},"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId","paths"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:index", 300000))
            .compensation(CompensationContract::new(CompensationKind::ExternalIrreversible, "discarded working-tree changes are externally irreversible"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes destructive branch/index mutations for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"discarded working-tree changes are externally irreversible","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::rebase_on_main", "worktree", EffectClass::ReversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .domain_module("worktree::git_workflow")
            .request_schema(json!({"additionalProperties":false,"properties":{"mainBranch":{"type":"string"},"sessionId":{"type":"string"},"strategy":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "rebase abort/manual reset is the recovery path while state exists"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes merge/rebase conflict workflows for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"rebase abort/manual reset is the recovery path while state exists","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::start_merge", "worktree", EffectClass::ReversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .domain_module("worktree::git_workflow")
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"sourceBranch":{"type":"string"},"strategy":{"type":"string"},"targetBranch":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId","sourceBranch","targetBranch"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "worktree.abortMerge is the inverse command while merge is active"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes merge/rebase conflict workflows for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"worktree.abortMerge is the inverse command while merge is active","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::list_conflicts", "worktree", EffectClass::PureRead, RiskLevel::Low, Some("worktree.read"))
            .domain_module("worktree::git_workflow")
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .build()?,
        CapabilityContract::new("worktree::resolve_conflict", "worktree", EffectClass::ReversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .domain_module("worktree::git_workflow")
            .request_schema(json!({"additionalProperties":false,"properties":{"path":{"type":"string"},"resolution":{"type":"string"},"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId","path","resolution"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "conflict files can be manually edited before continueMerge"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes merge/rebase conflict workflows for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"conflict files can be manually edited before continueMerge","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::continue_merge", "worktree", EffectClass::ReversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .domain_module("worktree::git_workflow")
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "manual reset/revert is required after merge completion"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes merge/rebase conflict workflows for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"manual reset/revert is required after merge completion","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::abort_merge", "worktree", EffectClass::ReversibleSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .domain_module("worktree::git_workflow")
            .request_schema(json!({"additionalProperties":false,"properties":{"reason":{"type":"string"},"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::InverseCommandAvailable, "startMerge can recreate the merge attempt if inputs still exist"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes merge/rebase conflict workflows for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"startMerge can recreate the merge attempt if inputs still exist","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?,
        CapabilityContract::new("worktree::resolve_conflicts_with_subagent", "worktree", EffectClass::ExternalSideEffect, RiskLevel::High, Some("worktree.write"))
            .approval_required(true)
            .domain_module("worktree::git_workflow")
            .request_schema(json!({"additionalProperties":false,"properties":{"sessionId":{"type":"string"},"workspaceId":{"type":"string"}},"required":["sessionId"],"type":"object"}))
            .response_schema(json!({"additionalProperties":true,"type":"object"}))
            .idempotency(IdempotencyContract::caller_session_engine_ledger())
            .resource_lease(ResourceLeaseRequirement::exclusive_template("worktree", "session:{sessionId}:workflow", 900000))
            .compensation(CompensationContract::new(CompensationKind::ManualOnly, "subagent conflict resolution writes files; manual review/reset remains the recovery path"))
            .high_risk_contract(json!({"approvalRequiredForAgentVisibility":true,"resourceLock":{"idTemplate":"session:{sessionId}:workflow","kind":"worktree","reason":"serializes merge/rebase conflict workflows for a session worktree","required":true,"ttlMs":900000},"rollbackOrCompensation":"subagent conflict resolution writes files; manual review/reset remains the recovery path","streamTopics":["resource.leases","catalog.changes"],"version":1}))
            .stream_topics(vec!["resource.leases", "catalog.changes"])
            .build()?
    ])
}
