name: TronMobile
options:
  bundleIdPrefix: com.tron
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  developmentLanguage: en
  generateEmptyDirectories: true
  createIntermediateGroups: true

configFiles:
  Debug-Beta: Configuration/Debug-Beta.xcconfig
  Release-Beta: Configuration/Release-Beta.xcconfig
  Debug-Prod: Configuration/Debug-Prod.xcconfig
  Release-Prod: Configuration/Release-Prod.xcconfig

configs:
  Debug-Beta: debug
  Release-Beta: release
  Debug-Prod: debug
  Release-Prod: release

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false
    DEVELOPMENT_TEAM: MYGKXH6TY4
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

targets:
  TronMobile:
    type: application
    platform: iOS
    sources:
      - path: Sources
        createIntermediateGroups: true
      - path: Sources/Resources/Fonts
        type: folder
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: YES
      configs:
        Debug-Beta:
          CODE_SIGN_ENTITLEMENTS: TronMobileDebug-Beta.entitlements
        Release-Beta:
          CODE_SIGN_ENTITLEMENTS: TronMobileRelease-Beta.entitlements
        Debug-Prod:
          CODE_SIGN_ENTITLEMENTS: TronMobileDebug-Prod.entitlements
        Release-Prod:
          CODE_SIGN_ENTITLEMENTS: TronMobileRelease-Prod.entitlements

  TronMobileTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        createIntermediateGroups: true
        optional: true
    dependencies:
      - target: TronMobile
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TronMobile.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/TronMobile"
        GENERATE_INFOPLIST_FILE: YES

schemes:
  TronMobile:
    build:
      targets:
        TronMobile: all
        TronMobileTests: [test]
    run:
      config: Debug-Prod
    test:
      config: Debug-Prod
      targets:
        - TronMobileTests
    profile:
      config: Release-Prod
    analyze:
      config: Debug-Prod
    archive:
      config: Release-Prod

  TronMobile-Beta:
    build:
      targets:
        TronMobile: all
        TronMobileTests: [test]
    run:
      config: Debug-Beta
    test:
      config: Debug-Beta
      targets:
        - TronMobileTests
    profile:
      config: Release-Beta
    analyze:
      config: Debug-Beta
    archive:
      config: Release-Beta
