//! In-process trigger dispatch runtime.
//!
//! Triggers are the engine's causal edge: a transport, schedule, queue, or
//! manual action fires a registered trigger, and the runtime turns that into a
//! normal invocation with trigger metadata attached.

use serde_json::Value;

use super::discovery::ActorKind;
use super::errors::EngineError;
use super::host::EngineHostHandle;
use super::ids::{ActorId, FunctionId, InvocationId, TraceId, TriggerId, WorkerId};
use super::invocation::{CausalContext, Invocation, InvocationResult};
use super::queue::{EnqueueInvocation, publish_queue_lifecycle_event};
use super::types::{DeliveryMode, FunctionRevision, TriggerDefinition};

struct PreparedTriggerInvocation {
    trigger: TriggerDefinition,
    invocation: Invocation,
}

/// Request to fire a registered trigger.
#[derive(Clone, Debug)]
pub struct TriggerDispatchRequest {
    /// Trigger to fire.
    pub trigger_id: TriggerId,
    /// Payload delivered to the target function.
    pub payload: Value,
    /// Actor that caused the trigger to fire.
    pub actor_id: ActorId,
    /// Actor kind.
    pub actor_kind: ActorKind,
    /// Authority scopes granted for this dispatch.
    pub authority_scopes: Vec<String>,
    /// Trace id to propagate, or generated by the runtime when absent.
    pub trace_id: Option<TraceId>,
    /// Parent invocation, if this trigger was caused by another function.
    pub parent_invocation_id: Option<InvocationId>,
    /// Optional session id.
    pub session_id: Option<String>,
    /// Optional workspace id.
    pub workspace_id: Option<String>,
    /// Optional idempotency key.
    pub idempotency_key: Option<String>,
    /// Delivery mode requested by the transport.
    pub delivery_mode: Option<DeliveryMode>,
}

impl TriggerDispatchRequest {
    /// Create a trigger dispatch request.
    #[must_use]
    pub fn new(
        trigger_id: TriggerId,
        payload: Value,
        actor_id: ActorId,
        actor_kind: ActorKind,
    ) -> Self {
        Self {
            trigger_id,
            payload,
            actor_id,
            actor_kind,
            authority_scopes: Vec::new(),
            trace_id: None,
            parent_invocation_id: None,
            session_id: None,
            workspace_id: None,
            idempotency_key: None,
            delivery_mode: None,
        }
    }
}

/// In-process trigger runtime.
pub struct EngineTriggerRuntime;

impl EngineTriggerRuntime {
    /// Fire a registered trigger and invoke its target through the host.
    pub async fn dispatch(
        handle: &EngineHostHandle,
        request: TriggerDispatchRequest,
    ) -> InvocationResult {
        match Self::prepare_invocation(handle, request).await {
            Ok(prepared) if prepared.invocation.delivery_mode == DeliveryMode::Enqueue => {
                let queue = prepared
                    .trigger
                    .config
                    .get("queue")
                    .and_then(Value::as_str)
                    .unwrap_or("default")
                    .to_owned();
                let invocation = prepared.invocation;
                let enqueue = EnqueueInvocation {
                    queue,
                    function_id: invocation.function_id.clone(),
                    target_revision: invocation.expected_function_revision,
                    payload: invocation.payload.clone(),
                    actor_id: invocation.causal_context.actor_id.clone(),
                    actor_kind: invocation.causal_context.actor_kind.clone(),
                    authority_grant_id: invocation.causal_context.authority_grant_id.clone(),
                    authority_scopes: invocation.causal_context.authority_scopes.clone(),
                    trace_id: invocation.causal_context.trace_id.clone(),
                    parent_invocation_id: invocation.causal_context.parent_invocation_id.clone(),
                    trigger_id: invocation.causal_context.trigger_id.clone(),
                    session_id: invocation.causal_context.session_id.clone(),
                    workspace_id: invocation.causal_context.workspace_id.clone(),
                    idempotency_key: invocation.causal_context.idempotency_key.clone(),
                };
                match handle.enqueue_invocation(enqueue).await {
                    Ok(item) => {
                        publish_queue_lifecycle_event(handle, "enqueue", &item, None).await;
                        handle.record_enqueued_invocation(invocation, &item).await
                    }
                    Err(error) => {
                        handle
                            .record_trigger_prepare_failure(
                                invocation,
                                prepared.trigger.owner_worker,
                                FunctionRevision(0),
                                error,
                            )
                            .await
                    }
                }
            }
            Ok(prepared) => handle.invoke(prepared.invocation).await,
            Err((trigger, error, request)) => {
                let worker_id = trigger.as_ref().map_or_else(
                    || WorkerId::new("engine").unwrap(),
                    |trigger| trigger.owner_worker.clone(),
                );
                let function_id = trigger.as_ref().map_or_else(
                    || FunctionId::new("engine::trigger_dispatch").unwrap(),
                    |trigger| trigger.target_function.clone(),
                );
                let mut context = CausalContext::new(
                    request.actor_id,
                    request.actor_kind,
                    trigger.as_ref().map_or_else(
                        || super::ids::AuthorityGrantId::new("missing").unwrap(),
                        |trigger| trigger.authority_grant.clone(),
                    ),
                    request.trace_id.unwrap_or_else(TraceId::generate),
                )
                .with_trigger_id(request.trigger_id);
                for scope in request.authority_scopes {
                    context = context.with_scope(scope);
                }
                if let Some(parent) = request.parent_invocation_id {
                    context = context.with_parent_invocation(parent);
                }
                if let Some(session_id) = request.session_id {
                    context = context.with_session_id(session_id);
                }
                if let Some(workspace_id) = request.workspace_id {
                    context = context.with_workspace_id(workspace_id);
                }
                if let Some(key) = request.idempotency_key {
                    context = context.with_idempotency_key(key);
                }
                context.delivery_mode = request.delivery_mode.unwrap_or(DeliveryMode::Sync);
                let invocation = Invocation::new_sync(function_id, request.payload, context)
                    .with_delivery_mode(request.delivery_mode.unwrap_or(DeliveryMode::Sync));
                handle
                    .record_trigger_prepare_failure(
                        invocation,
                        worker_id,
                        FunctionRevision(0),
                        error,
                    )
                    .await
            }
        }
    }

    async fn prepare_invocation(
        handle: &EngineHostHandle,
        request: TriggerDispatchRequest,
    ) -> std::result::Result<
        PreparedTriggerInvocation,
        (
            Option<TriggerDefinition>,
            EngineError,
            TriggerDispatchRequest,
        ),
    > {
        let trigger = match handle.inspect_trigger(&request.trigger_id).await {
            Ok(trigger) => trigger,
            Err(error) => return Err((None, error, request)),
        };

        let requested_delivery = request.delivery_mode.unwrap_or(trigger.delivery_mode);
        if requested_delivery != trigger.delivery_mode {
            let delivery_mode = trigger.delivery_mode;
            return Err((
                Some(trigger),
                EngineError::PolicyViolation(format!(
                    "trigger {} only supports {:?} delivery for this registration",
                    request.trigger_id, delivery_mode
                )),
                request,
            ));
        }

        let mut context = CausalContext::new(
            request.actor_id.clone(),
            request.actor_kind,
            trigger.authority_grant.clone(),
            request.trace_id.clone().unwrap_or_else(TraceId::generate),
        )
        .with_trigger_id(request.trigger_id.clone());
        for scope in &request.authority_scopes {
            context = context.with_scope(scope.clone());
        }
        if let Some(parent) = &request.parent_invocation_id {
            context = context.with_parent_invocation(parent.clone());
        }
        if let Some(session_id) = &request.session_id {
            context = context.with_session_id(session_id.clone());
        }
        if let Some(workspace_id) = &request.workspace_id {
            context = context.with_workspace_id(workspace_id.clone());
        }
        if let Some(key) = &request.idempotency_key {
            context = context.with_idempotency_key(key.clone());
        }

        let mut invocation = Invocation::new_sync(
            trigger.target_function.clone(),
            request.payload.clone(),
            context,
        )
        .with_delivery_mode(trigger.delivery_mode);
        if let Some(revision) = trigger.target_revision {
            invocation = invocation.expecting_revision(revision);
        }
        Ok(PreparedTriggerInvocation {
            trigger,
            invocation,
        })
    }
}
