//! In-process trigger dispatch runtime.
//!
//! Triggers are the engine's causal edge: a transport, schedule, queue, or
//! manual action fires a registered trigger, and the runtime turns that into a
//! normal invocation with trigger metadata attached.

use serde_json::Value;
use std::collections::BTreeMap;

use super::discovery::ActorKind;
use super::errors::EngineError;
use super::host::EngineHostHandle;
use super::ids::{ActorId, FunctionId, InvocationId, TraceId, TriggerId, WorkerId};
use super::invocation::{
    CausalContext, Invocation, InvocationResult, RUNTIME_METADATA_TRIGGER_DEPTH,
    RUNTIME_METADATA_TRIGGER_PATH,
};
use super::queue::{EnqueueInvocation, publish_queue_lifecycle_event};
use super::types::{DeliveryMode, FunctionRevision, TriggerDefinition};

const DEFAULT_TRIGGER_MAX_DEPTH: u32 = 8;

struct PreparedTriggerInvocation {
    trigger: TriggerDefinition,
    invocation: Invocation,
}

/// Request to fire a registered trigger.
#[derive(Clone, Debug)]
pub struct TriggerDispatchRequest {
    /// Trigger to fire.
    pub trigger_id: TriggerId,
    /// Payload delivered to the target function.
    pub payload: Value,
    /// Actor that caused the trigger to fire.
    pub actor_id: ActorId,
    /// Actor kind.
    pub actor_kind: ActorKind,
    /// Authority scopes granted for this dispatch.
    pub authority_scopes: Vec<String>,
    /// Engine-internal runtime metadata propagated from trusted transports.
    pub runtime_metadata: BTreeMap<String, String>,
    /// Trace id to propagate, or generated by the runtime when absent.
    pub trace_id: Option<TraceId>,
    /// Parent invocation, if this trigger was caused by another function.
    pub parent_invocation_id: Option<InvocationId>,
    /// Optional session id.
    pub session_id: Option<String>,
    /// Optional workspace id.
    pub workspace_id: Option<String>,
    /// Optional idempotency key.
    pub idempotency_key: Option<String>,
    /// Delivery mode requested by the transport.
    pub delivery_mode: Option<DeliveryMode>,
}

impl TriggerDispatchRequest {
    /// Create a trigger dispatch request.
    #[must_use]
    pub fn new(
        trigger_id: TriggerId,
        payload: Value,
        actor_id: ActorId,
        actor_kind: ActorKind,
    ) -> Self {
        Self {
            trigger_id,
            payload,
            actor_id,
            actor_kind,
            authority_scopes: Vec::new(),
            runtime_metadata: BTreeMap::new(),
            trace_id: None,
            parent_invocation_id: None,
            session_id: None,
            workspace_id: None,
            idempotency_key: None,
            delivery_mode: None,
        }
    }
}

/// In-process trigger runtime.
pub struct EngineTriggerRuntime;

impl EngineTriggerRuntime {
    /// Fire a registered trigger and invoke its target through the host.
    pub async fn dispatch(
        handle: &EngineHostHandle,
        request: TriggerDispatchRequest,
    ) -> InvocationResult {
        match Self::prepare_invocation(handle, request).await {
            Ok(prepared) if prepared.invocation.delivery_mode == DeliveryMode::Enqueue => {
                let queue = prepared
                    .trigger
                    .config
                    .get("queue")
                    .and_then(Value::as_str)
                    .unwrap_or("default")
                    .to_owned();
                let invocation = prepared.invocation;
                let enqueue = EnqueueInvocation {
                    queue,
                    function_id: invocation.function_id.clone(),
                    target_revision: invocation.expected_function_revision,
                    payload: invocation.payload.clone(),
                    actor_id: invocation.causal_context.actor_id.clone(),
                    actor_kind: invocation.causal_context.actor_kind.clone(),
                    authority_grant_id: invocation.causal_context.authority_grant_id.clone(),
                    authority_scopes: invocation.causal_context.authority_scopes.clone(),
                    runtime_metadata: invocation.causal_context.runtime_metadata.clone(),
                    trace_id: invocation.causal_context.trace_id.clone(),
                    parent_invocation_id: invocation.causal_context.parent_invocation_id.clone(),
                    trigger_id: invocation.causal_context.trigger_id.clone(),
                    session_id: invocation.causal_context.session_id.clone(),
                    workspace_id: invocation.causal_context.workspace_id.clone(),
                    idempotency_key: invocation.causal_context.idempotency_key.clone(),
                };
                match handle.enqueue_invocation(enqueue).await {
                    Ok(item) => {
                        publish_queue_lifecycle_event(handle, "enqueue", &item, None).await;
                        handle.record_enqueued_invocation(invocation, &item).await
                    }
                    Err(error) => {
                        handle
                            .record_trigger_prepare_failure(
                                invocation,
                                prepared.trigger.owner_worker,
                                FunctionRevision(0),
                                error,
                            )
                            .await
                    }
                }
            }
            Ok(prepared) if prepared.invocation.delivery_mode == DeliveryMode::Void => {
                handle.invoke_trigger_target(prepared.invocation).await
            }
            Ok(prepared) => handle.invoke(prepared.invocation).await,
            Err((trigger, error, request)) => {
                let worker_id = trigger.as_ref().map_or_else(
                    || WorkerId::new("engine").unwrap(),
                    |trigger| trigger.owner_worker.clone(),
                );
                let function_id = trigger.as_ref().map_or_else(
                    || FunctionId::new("engine::trigger_dispatch").unwrap(),
                    |trigger| trigger.target_function.clone(),
                );
                let mut context = CausalContext::new(
                    request.actor_id,
                    request.actor_kind,
                    trigger.as_ref().map_or_else(
                        || super::ids::AuthorityGrantId::new("missing").unwrap(),
                        |trigger| trigger.authority_grant.clone(),
                    ),
                    request.trace_id.unwrap_or_else(TraceId::generate),
                )
                .with_trigger_id(request.trigger_id);
                for scope in request.authority_scopes {
                    context = context.with_scope(scope);
                }
                for (key, value) in request.runtime_metadata {
                    context = context.with_runtime_metadata(key, value);
                }
                if let Some(parent) = request.parent_invocation_id {
                    context = context.with_parent_invocation(parent);
                }
                if let Some(session_id) = request.session_id {
                    context = context.with_session_id(session_id);
                }
                if let Some(workspace_id) = request.workspace_id {
                    context = context.with_workspace_id(workspace_id);
                }
                if let Some(key) = request.idempotency_key {
                    context = context.with_idempotency_key(key);
                }
                context.delivery_mode = request.delivery_mode.unwrap_or(DeliveryMode::Sync);
                let invocation = Invocation::new_sync(function_id, request.payload, context)
                    .with_delivery_mode(request.delivery_mode.unwrap_or(DeliveryMode::Sync));
                handle
                    .record_trigger_prepare_failure(
                        invocation,
                        worker_id,
                        FunctionRevision(0),
                        error,
                    )
                    .await
            }
        }
    }

    async fn prepare_invocation(
        handle: &EngineHostHandle,
        request: TriggerDispatchRequest,
    ) -> std::result::Result<
        PreparedTriggerInvocation,
        (
            Option<TriggerDefinition>,
            EngineError,
            TriggerDispatchRequest,
        ),
    > {
        let trigger = match handle.inspect_trigger(&request.trigger_id).await {
            Ok(trigger) => trigger,
            Err(error) => return Err((None, error, request)),
        };

        let requested_delivery = request.delivery_mode.unwrap_or(trigger.delivery_mode);
        if requested_delivery != trigger.delivery_mode {
            let delivery_mode = trigger.delivery_mode;
            return Err((
                Some(trigger),
                EngineError::PolicyViolation(format!(
                    "trigger {} only supports {:?} delivery for this registration",
                    request.trigger_id, delivery_mode
                )),
                request,
            ));
        }
        let cascade = match trigger_cascade_metadata(&trigger, &request) {
            Ok(cascade) => cascade,
            Err(error) => return Err((Some(trigger), error, request)),
        };

        let mut context = CausalContext::new(
            request.actor_id.clone(),
            request.actor_kind,
            trigger.authority_grant.clone(),
            request.trace_id.clone().unwrap_or_else(TraceId::generate),
        )
        .with_trigger_id(request.trigger_id.clone());
        for scope in &request.authority_scopes {
            context = context.with_scope(scope.clone());
        }
        for (key, value) in &request.runtime_metadata {
            if key == RUNTIME_METADATA_TRIGGER_DEPTH || key == RUNTIME_METADATA_TRIGGER_PATH {
                continue;
            }
            context = context.with_runtime_metadata(key.clone(), value.clone());
        }
        context = context
            .with_runtime_metadata(
                RUNTIME_METADATA_TRIGGER_DEPTH,
                cascade.next_depth.to_string(),
            )
            .with_runtime_metadata(RUNTIME_METADATA_TRIGGER_PATH, cascade.next_path);
        if let Some(parent) = &request.parent_invocation_id {
            context = context.with_parent_invocation(parent.clone());
        }
        if let Some(session_id) = &request.session_id {
            context = context.with_session_id(session_id.clone());
        }
        if let Some(workspace_id) = &request.workspace_id {
            context = context.with_workspace_id(workspace_id.clone());
        }
        if let Some(key) = &request.idempotency_key {
            context = context.with_idempotency_key(key.clone());
        }

        let mut invocation = Invocation::new_sync(
            trigger.target_function.clone(),
            request.payload.clone(),
            context,
        )
        .with_delivery_mode(trigger.delivery_mode);
        if let Some(revision) = trigger.target_revision {
            invocation = invocation.expecting_revision(revision);
        }
        Ok(PreparedTriggerInvocation {
            trigger,
            invocation,
        })
    }
}

struct TriggerCascadeMetadata {
    next_depth: u32,
    next_path: String,
}

fn trigger_cascade_metadata(
    trigger: &TriggerDefinition,
    request: &TriggerDispatchRequest,
) -> Result<TriggerCascadeMetadata, EngineError> {
    let current_depth = trigger_depth(&request.runtime_metadata)?;
    let mut path = trigger_path(&request.runtime_metadata)?;
    let max_depth = trigger.max_depth.unwrap_or(DEFAULT_TRIGGER_MAX_DEPTH);
    if current_depth > max_depth {
        return Err(EngineError::PolicyViolation(format!(
            "trigger cascade depth {current_depth} exceeds max depth {max_depth} for {}",
            trigger.id
        )));
    }
    if path.iter().any(|id| id == trigger.id.as_str()) {
        return Err(EngineError::PolicyViolation(format!(
            "trigger cascade loop detected for {}",
            trigger.id
        )));
    }
    path.push(trigger.id.to_string());
    let next_path = serde_json::to_string(&path).map_err(|error| {
        EngineError::PolicyViolation(format!("trigger cascade path is not serializable: {error}"))
    })?;
    Ok(TriggerCascadeMetadata {
        next_depth: current_depth.saturating_add(1),
        next_path,
    })
}

fn trigger_depth(metadata: &BTreeMap<String, String>) -> Result<u32, EngineError> {
    let Some(value) = metadata.get(RUNTIME_METADATA_TRIGGER_DEPTH) else {
        return Ok(0);
    };
    value.parse::<u32>().map_err(|_| {
        EngineError::PolicyViolation(format!(
            "trigger cascade depth metadata must be an unsigned integer, got {value:?}"
        ))
    })
}

fn trigger_path(metadata: &BTreeMap<String, String>) -> Result<Vec<String>, EngineError> {
    let Some(value) = metadata.get(RUNTIME_METADATA_TRIGGER_PATH) else {
        return Ok(Vec::new());
    };
    serde_json::from_str::<Vec<String>>(value).map_err(|error| {
        EngineError::PolicyViolation(format!(
            "trigger cascade path metadata must be a JSON string array: {error}"
        ))
    })
}
